### ISSUE TITLE
Returning the SAT point which violate the setup conditions 

### ISSUE THREAD

**Issue by sparth95** [NeuralNetworkVerification/Marabou#101]
While creating a demo for today's presentation, I came across a point where Marabou terminates with a SAT point, but the SAT point does not satisfy the constraints of the problem.

Problem setup:
We are working on MNIST images, we are trying to find adversarial examples for an image within a given delta. The input here is classified as 8. We are trying to find a minimum delta, such that perturbations < delta leads to image being misclassified as 3.

` MarabouUtils.addInequality(net, [net.outputVars[0][pred], net.outputVars[0][ae_target]], [1, -1], 0)`
This inequality is the constraint that we are trying to solve. `pred` is the initial prediction(8 for us). `ae_target` is the adversarial label we are trying to get image misclassified as.

Our expectation is that if we get a SAT point then the output value for `pred <= ae_target`. In the given example, while they are close, it still is the case that `pred > ae_target`. The values we are getting is: 
[[-6.25324207 -7.91382846 -1.01699024  **0.30267924** -3.63097583 -1.75347436
  -7.64562634 -2.79832181  **0.30273349** -2.61049726]].

I have attached the python file and the example input. The example takes a while to run on the master branch, but runs in around 10 seconds on using out PR with smart-fix flag turned on.
[files.zip](https://github.com/guykatzz/Marabou/files/2626330/files.zip)

**Comment by idan0610** [comment]
This issue has most likely become stale and is being closed. If the problem persists, please contact us or open a new issue.
