### ISSUE TITLE
MarabouNetworkTF support for StridedSlice, ExpandDims, Squeeze and Softmax operations

### ISSUE THREAD

**Issue by adethise** [NeuralNetworkVerification/Marabou#156]
The operations StridedSlice, ExpandDims, Squeeze and Softmax are not currently supported when importing a TF graph from the Python interface.

They will fall through the [getValues](https://github.com/guykatzz/Marabou/blob/master/maraboupy/MarabouNetworkTF.py#L179) and [makeNeuronEquations](https://github.com/guykatzz/Marabou/blob/master/maraboupy/MarabouNetworkTF.py#L481) (except for StridedSlice) functions and reach the NotImplementedError at the end.

Is support for those operations planned and/or is there an alternative approach to read and verify a network using them?

**Comment by AleksandarZeljic** [comment]
Did you find a workaround for this or do you still need these operators?

**Comment by adethise** [comment]
We used a workaround by manually creating an equivalent model using only supported operators and copying the weights over to the new model.

**Comment by AleksandarZeljic** [comment]
Thanks for raising these issues, and following up, we do not intend to support additional constructs at this time.
