### ISSUE TITLE
Optimize SymbolicBoundTightener by using sparse matrices

### ISSUE THREAD

**Issue by anwu1219** [NeuralNetworkVerification/Marabou#161]
The symbolic bound tightener appears to become runtime bottleneck for larger networks.
Perhaps using packages such as Blas/Lapack for matrix operations.

**Comment by ahmed-irfan** [comment]
can you share a benchmark that shows this behavior?

**Comment by anwu1219** [comment]
Here is a network that takes much longer to solve when symbolic bound tightener is turned on (option can be set in GlobalConfiguration.cpp).
The difference can be seen even without a property file.

[mnist_10_layer.nnet.zip](https://github.com/guykatzz/Marabou/files/3488462/mnist_10_layer.nnet.zip)

**Comment by anwu1219** [comment]
Closing this issue since we support using OpenBLAS in SBT
