### ISSUE TITLE
Loading Pytorch Models

### ISSUE THREAD

**Issue by darioguidotti** [NeuralNetworkVerification/Marabou#190]
Hello,

I am trying to find a way to verify a set of models created and 
learned using pytorch but I am finding some difficulties.

Converting the models to the ONNX format and then to tensorflow protobuffer
(using onnx-tf) seems to modify the model with unnecessary operations which
are currently not supported by Marabou (e.g., GatherV2).

My models are convolutional and fully connected networks which only use Conv2d, Linear and MaxPool2d layers and the torch reshape function in forward of the model.

Do you have any advice on how to solve this problem?

Thank you!

**Comment by kjulian3** [comment]
Support has been added for the tensorflow network layers in this network. An ONNX parser has been created, which can handle networks translated to ONNX from pytorch.
