### ISSUE TITLE
Several places for defining the same configuration variables

### ISSUE THREAD

**Issue by Yoni-Mantzur** [NeuralNetworkVerification/Marabou#209]
Hey, 

There are several places where we can define configuration variables - `GlobalConfiguration` and `Options` - this motivates a non-uniform defining behavior and bugs prone - for example -  the default value of `PREPROCESSOR_PL_CONSTRAINTS_ADD_AUX_EQUATIONS` is defined in `GlobalConfiguration` as true but in `Options` as false value

**Comment by AleksandarZeljic** [comment]
It's on our to do list, closing for now.
