### ISSUE TITLE
Problem with extremely sparse networks

### ISSUE THREAD

**Issue by darioguidotti** [NeuralNetworkVerification/Marabou#217]
Hello,

I am using Marabou to test constraints on very sparse networks (i.e., in which many of the weights are 0 or near to 0, for example, 10^-8).

When I test some property which the network should verify (e.g., the corresponding adversarial example was found using a statistical method) Marabou instantly (in less than a second) gives that the problem is UNSAT.

May it be possible that Marabou is subject to some kind of problem in the building of the representation of the network?

In attachment, you can find a .zip in which I have set up some scripts
 in order to reproduce the issue.

Thank you for your time!

[marabou_test.zip](https://github.com/NeuralNetworkVerification/Marabou/files/4184537/marabou_test.zip)

**Comment by idan0610** [comment]
This issue has most likely become stale and is being closed. The values ​​of the weights in the network are extremely low (but not 0), and this causes problems of numerical precision. If this topic is still relevant, please open a new issue.
