### ISSUE TITLE
Build error "use of undeclared identifier 'CLOCK_MONOTONIC'" on mac

### ISSUE THREAD

**Issue by castrong** [NeuralNetworkVerification/Marabou#220]
I am getting the following build error after running `cmake --build .` while following the "Build Instructions for Linux or MacOS" in the README. 

<img width="836" alt="build_error" src="https://user-images.githubusercontent.com/12678374/74306121-84272a80-4d16-11ea-9f70-3186d78719be.png">

I'm new to the codebase and haven't attempted any changes to the build system. I'd appreciate any suggestions on next steps or fixes!

Thank you!
Chris

**Comment by ahmed-irfan** [comment]
what is your MacOS version?

**Comment by castrong** [comment]
It is 10.13.3 (High Sierra)

**Comment by clazarus** [comment]
I was able to build a fresh copy of Marabou with no issues at all. I have macOS Catalina 10.15.3 (19D76). 

@castrong could you please copy what you get when you run:
`clang --version `
and
`cmake --version`


on your terminal?

For reference, I have:
`Apple clang version 11.0.0 (clang-1100.0.33.17)`
`Target: x86_64-apple-darwin19.3.0`
`Thread model: posix`
and
`cmake version 3.13.4`

I did a bit of research online and it appears that `CLOCK_MONOTONIC` was introduced in macOS Sierra 10.12 (September 2016, XCode 8) so it should work.

**Comment by castrong** [comment]
I get:

`clang --version`

Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin17.4.0
Thread model: posix

`cmake --version`
cmake version 3.9.6

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by castrong** [comment]
I ended up fixing this issue by updating clang on my computer.
