### ISSUE TITLE
Example output values for ACAS XU networks

### ISSUE THREAD

**Issue by vtjeng** [NeuralNetworkVerification/Marabou#225]
I'm importing the [neural networks for ACAS XU ](https://github.com/NeuralNetworkVerification/Marabou/tree/master/resources/nnet/acasxu) to try to verify the same properties as in Appendix 6 of the [Reluplex paper](https://arxiv.org/abs/1702.01135), and want to make sure that I'm getting conventions (e.g. row vs. column) correct. 

I've followed the code in the main Reluplex repository https://github.com/guykatzz/ReluplexCav2017/blob/master/nnet/nnet.cpp but just want to make sure that I'm not making any silly errors. In particular, I'd like to make sure that I'm getting the logic around [normalization](https://github.com/guykatzz/ReluplexCav2017/blob/e2e48b2980f76bdff74787427f43fff3b26a45a4/nnet/nnet.cpp#L215-L264) done correctly --- it seems like [neither the output nor input is to be normalized](https://github.com/guykatzz/ReluplexCav2017/blob/c6fcc3308c3edcf1c155e2b9625ac924d06e099b/nnet/AcasNeuralNetwork.h#L103-L106), but I just want to make sure --- and having values to work with would be extremely helpful.

A single set of input / output values fed through any of these networks should be enough for a sanity check - is this available somewhere?

**Comment by kjulian3** [comment]
More information on the NNet format along with test functions for the networks can be found [here](https://github.com/sisl/NNet). Input/output normalization is needed to evaluate the networks correctly if you are using the range, angle, speeds, etc. as inputs to the networks and want to compute the scores of the different advisories (network outputs). You can also define properties in the normalized input space if desired, but those properties are less interpretable.

I think it would be helpful to have a test set of input/output pairs for sanity checks. I'll work on adding a few examples to this repository. For now, here are a couple sanity check points using the network **ACASXU_experimental_v2a_1_1.nnet**

**Scenario where intruder is 1000 ft directly in front of ownship and heading in a direction roughly 90 degrees to the *right* of ownship's flight direction, both flying at 100 ft/s**
Input: [1000.0, 0.0, -1.5, 100.0, 100.0] 
Output: [177.87553729, 173.75796115, 193.05920806, 153.07876146, 195.00495022]
Best action (minimum-score): Fourth action, Strong Left turn

**Scenario where intruder is 1000 ft directly in front of ownship and heading in a direction roughly 90 degrees to the *left* of ownship's flight direction, both flying at 100 ft/s**
Input: [1000.0, 0.0, 1.5, 100.0, 100.0] 
Output: [176.62124824, 192.18261158, 172.41723949, 195.5359213, 153.49976799]
Best action (minimum-score): Fifth action, Strong Right turn

These points were generated using the NNet repository. If the NNet repository is cloned and on your PYTHONPATH, you can run:

```
from NNet.python.nnet import NNet
nnet = NNet("ACASXU_experimental_v2a_1_1.nnet")
nnet.evaluate_network([1000.0, 0.0, -1.5, 100.0, 100.0])
>>> array([177.87553729, 173.75796115, 193.05920806, 153.07876146,
       195.00495022])
```

**Comment by kjulian3** [comment]
Tests have been added for maraboupy's NNet parser, which list expected input/output pairs. 

https://github.com/NeuralNetworkVerification/Marabou/blob/master/maraboupy/test/test_nnet.py

By default, Marabou expects the user to handle input/output normalization, but a new option "normalize" was added so that the properties can be defined in the original input space while Marabou handles the normalization.  The properties defined in test_nnet.py all define the same points, either before or after input/output normalization.

**Comment by tzuyichiu** [comment]
Hi, thanks for the provided examples which were of great help. However is it possible to provide some information about how *tau* (time until loss of vertical separation) has been discretized? If I understand correctly, the file **ACASXU_experimental_v2a_1_1**, for example, corresponds to the case where *a_prev* must be the first action, Clear of Conflict, and *tau* the first out of nine discrete values, but what are they exactly?
Also, are the output actions ordered in the following way: Clear of Conflict, Weak Left turn, Weak Right turn, Strong Left turn, Strong Right turn? Thanks in advance for any additional information!

**Comment by kjulian3** [comment]
Yes, the discretizations are:

1. a_prev: [Clear of Conflict, Weak Left, Weak Right, Strong Left, and Strong Right]
2. tau: [0, 1, 5, 10, 20, 40, 60, 80, 100]

The two indices at the end of the filenames are the indices to these a_prev and tau vectors (using 1-based indexing). So network ...2_3.nnet refers to previous advisory Weak Left with tau=5 seconds. 

This information and other information can be found on page 29 of the Reluplex paper: https://arxiv.org/pdf/1702.01135.pdf
