### ISSUE TITLE
When running `Marabou.cpp` - asserts arn't called even with debug mode 

### ISSUE THREAD

**Issue by Yoni-Mantzur** [NeuralNetworkVerification/Marabou#226]
When running the main module - `Marabou.cpp` on debug mode, assertions are not called. Probably due to missing `--DDEBUG` flag

**Comment by yuvaljacoby** [comment]
Are you sure clion is adding DEBUG flag? I know that usually NDEBUG is used to indicate release mode (anyway that is what cmake is doing).
I just pushed [use_ndebug](https://github.com/NeuralNetworkVerification/Marabou/tree/use_ndebug) branch,can you try it out? if it doesn't t work take a look at src/common/Debug.h or late me know

**Comment by Yoni-Mantzur** [comment]
@yuvaljacoby the fix looks good, tested on `debug` mode and `release` mode.
