### ISSUE TITLE
build problems on mac

### ISSUE THREAD

**Issue by chelseas** [NeuralNetworkVerification/Marabou#238]
tried the new cmake build and got this error even tho pybind11 was already installed in my conda env. also why are yoou trying to run wget? Not everyone's host is running linux:
```didnt find pybind, getting it
downloading pybind
/Users/Chelsea/Dropbox/AAHAA/src/Marabou/tools/download_pybind11.sh: line 10: wget: command not found
unzipping pybind
tar: Error opening archive: Failed to open 'pybind11_2_3_0.tar.gz'
CMake Error at CMakeLists.txt:201 (add_subdirectory):
  add_subdirectory given source
  "/Users/Chelsea/Dropbox/AAHAA/src/Marabou/tools/pybind11-2.3.0" which is
  not an existing directory.


CMake Error at CMakeLists.txt:202 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".


-- Configuring incomplete, errors occurred!
See also "/Users/Chelsea/Dropbox/AAHAA/src/Marabou/CMakeFiles/CMakeOutput.log".
```

**Comment by anwu1219** [comment]
You need to install wget in order to use this new build system. Sorry this was not clearly documented.
On MacOS, you can install wget through homebrew by calling
   `brew install wget`
After this, you should be able to build successfully.

**Comment by chelseas** [comment]
but why is it trying to install pybind if I already have it installed in my conda env?

**Comment by anwu1219** [comment]
> but why is it trying to install pybind if I already have it installed in my conda env?
This is because currently we only check whether pybind11 is installed in Marabou/tool/ but not globally in the system. https://github.com/NeuralNetworkVerification/Marabou/blob/742247769565f433a18bcadbc2ecfbc514c275de/CMakeLists.txt#L197

**Comment by anwu1219** [comment]
> but why is it trying to install pybind if I already have it installed in my conda env?

This is because currently we only check whether pybind11 is installed in Marabou/tool/ but not globally in the system. https://github.com/NeuralNetworkVerification/Marabou/blob/742247769565f433a18bcadbc2ecfbc514c275de/CMakeLists.txt#L197

**Comment by chelseas** [comment]
Seems like an oversight, but it's not critical so I'll close the issue.
