### ISSUE TITLE
transA and transB support for GEMM

### ISSUE THREAD

**Issue by samuelemarro** [NeuralNetworkVerification/Marabou#239]
ONNX's GEMM operation supports the optional parameters `transA` and `transB`, which respectively transpose the input and weight tensors. Unfortunately, maraboupy assumes that both of these parameters are false. This causes an assertion error, since if a tensor is transposed, the dimensions will be reversed:
https://github.com/NeuralNetworkVerification/Marabou/blob/41ccc59a1bcadd99b8038317e25cdba34a017677/maraboupy/MarabouNetworkONNX.py#L490

Since PyTorch converts `nn.Linear` modules into GEMM operations with `transB=1`, many exported PyTorch models cannot be opened by Marabou.

**Comment by kjulian3** [comment]
Thanks for pointing this out. The test networks I created didn't use those options, so they didn't get implemented. There may be other ONNX options or functionality that hasn't been supported yet, so please let us know if you run into other issues so we can make improvements. I'll work on a pr for transA and transB.

**Comment by samuelemarro** [comment]
Thank you.

**Comment by kjulian3** [comment]
@samuelemarro I submitted pull request #242. Can you take a look and let me know if this solves your issue?

**Comment by samuelemarro** [comment]
Tested with a simple FeedForward network and some dummy inputs. It converts the model without errors and Marabou's output matches both PyTorch's and ONNX's output. Thank you for your help.
