### ISSUE TITLE
Possible misspell in MarabouNetworkONNX.py

### ISSUE THREAD

**Issue by samuelemarro** [NeuralNetworkVerification/Marabou#240]
While I was looking for a workaround for #239, I stumbled upon the following line:
https://github.com/NeuralNetworkVerification/Marabou/blob/41ccc59a1bcadd99b8038317e25cdba34a017677/maraboupy/MarabouNetworkONNX.py#L345
`self` does not have the `constant` attribute, and apparently it isn't used anywhere else. Given the context, could it actually be `self.constantMap`?

**Comment by kjulian3** [comment]
Yes it should be constantMap, thanks for pointing this out.
