### ISSUE TITLE
Testing framework for Maraboupy

### ISSUE THREAD

**Issue by kjulian3** [NeuralNetworkVerification/Marabou#244]
We don't have a formal testing framework yet for maraboupy and the input parsers. I have a set of test networks I've been using to validate the tensorflow and onnx parsers, but incorporating these networks into automatic tests would tell us what parts of the code are still untested and ensure that future code changes don't introduce new bugs.

I can work on setting up the framework, but I'm not sure the best way to do that. Does anyone have any recommendations for setting up the testing framework, or is someone else currently working on this?

**Comment by yuvaljacoby** [comment]
I agree this is important! 
Not only to make sure code does not break, it's also a great entry point for new users.

For framework I am usually working with pytest
Can you start and write some tests? 
I can later add them to the build process and travis
