### ISSUE TITLE
Using the DnC mode

### ISSUE THREAD

**Issue by teobaluta** [NeuralNetworkVerification/Marabou#259]
Hi,

I am trying out Marabou with the following options:
```
    options = Marabou.createOptions(dnc=True, verbosity=0,
                                    initialDivides=16,
                                    timeoutInSeconds=200,
                                    numWorkers=10)
```
I noticed that the workers print out `TIMEOUT` followed by `Quit requested by manager!`. 
```
Worker 1: Query 247 TIMEOUT, 66274 tasks remaining
Worker 8: Query 248 TIMEOUT, 66277 tasks remaining
Worker 6: Query 249 TIMEOUT, 66280 tasks remaining
Worker 7: Query 250 TIMEOUT, 66283 tasks remaining
Worker 5: Query 255 QUIT_REQUESTED, 66286 tasks remaining
Quit requested by manager!
Worker 6: Query 259 QUIT_REQUESTED, 66286 tasks remaining
Quit requested by manager!
Worker 4: Query 254 QUIT_REQUESTED, 66286 tasks remaining
Quit requested by manager!
Worker 2: Query 256 QUIT_REQUESTED, 66286 tasks remaining
Quit requested by manager!
Worker 1: Query 257 QUIT_REQUESTED, 66286 tasks remaining
Quit requested by manager!
Worker 8: Query 258 QUIT_REQUESTED, 66286 tasks remaining
Quit requested by manager!
Worker 9: Query 251 QUIT_REQUESTED, 66286 tasks remaining
Quit requested by manager!
Worker 7: Query 260 QUIT_REQUESTED, 66286 tasks remaining
Quit requested by manager!
Worker 0: Query 252 QUIT_REQUESTED, 66286 tasks remaining
Quit requested by manager!
Worker 3: Query 253 QUIT_REQUESTED, 66286 tasks remaining
Quit requested by manager!
```

I check the return value of the query as follows:
```
    sat_vals, stats = MarabouCore.solve(network_query, options=options)

    if stats.hasTimedOut():
        print("TO")
    else:
        if len(sat_vals) == 0:
            print("UNSAT")
        else:
            print("SAT")
```

Is this the correct way of parsing the returned result when DnC mode is used? I am a bit confused by the worker's results -- I was expecting to see some UNSAT value in one of the worker threads.

Thank you,
Teodora

**Comment by anwu1219** [comment]
Hi Teodora, 

Thanks for your interests in our tool. What is the network architecture that you're trying to analyze (e.g. # of Neurons, # of inputs)? If the input dimension is very high, dnc might not be helpful. 
In any case, the dnc mode create 2 ^ [initialDivides] sub-regions initially. So if you want to create 16 sub-queries, you can set that parameter to 4. I'd also suggest setting initialTimeout to a larger number (e.g., 60 instead of 5) if the query is hard.
If you provide me with the benchmark, I might have a better idea of what would be a reasonable set of parameters.

**Comment by teobaluta** [comment]
Hi Andrew,

Thanks for the suggestions, I will try with these parameters! However, I'm still puzzled as to how should I parse the output of Marabou. In this case the `stats.hasTimedOut` returns `False`  -- should it not return `True` given the printed output? Is there any other way to check the Marabou's result in DnC mode?

Here's my full script.

```
import sys
import time
import csv
import numpy as np

import maraboupy
from maraboupy import Marabou
from maraboupy import MarabouNetwork
from maraboupy import MarabouCore

def test(pbfile, testfile):
    epsilon = 0.1
    with open(testfile) as csvfile:
        tests = csv.reader(csvfile, delimiter=',')
        for i, test in enumerate(tests):
            image = np.float64(test[1:len(test)])/np.float64(255)
            correct_label = int(test[0])
            var_bounds = []
            for x in range(len(image)):
                lb = 0.0 if image[x] - epsilon < 0 else image[x] - epsilon
                ub = 1.0 if image[x] + epsilon > 1 else image[x] + epsilon
                var_bounds.append((lb, ub))

    network = Marabou.read_tf(pbfile)

    # Set input bounds
    inputVars = network.inputVars[0]
    for i in range(len(inputVars)):
        network.setLowerBound(inputVars[i], var_bounds[i][0])
        network.setUpperBound(inputVars[i], var_bounds[i][1])

    network_query = network.getMarabouQuery()
    MarabouCore.saveQuery(network_query, "query")
    e = MarabouCore.Equation(MarabouCore.Equation.GE)
    #e.addAddend(1, 857)
    #e.setScalar(5.01)
    e.addAddend(1, 830)
    e.setScalar(0.34)
    network_query.addEquation(e)

    options = Marabou.createOptions(dnc=True, verbosity=0,
                                    initialDivides=16,
                                    timeoutInSeconds=200,
                                    numWorkers=10)

    start_time = time.time()
    sat_vals, stats = MarabouCore.solve(network_query, options=options)

    print(stats.hasTimedOut())
    if stats.hasTimedOut():
        print("TO")
    else:
        if len(sat_vals) == 0:
            print("UNSAT")
        else:
            print("SAT")

if __name__ == "__main__":
    test(sys.argv[1], sys.argv[2])
```

I've attached this script and the inputs to the script in the zip file. Run as `python marabou-snippet.py test_model.pb mnist_test_0.csv`. 

Thank you for your help,
Teodora

[marabou-query.zip](https://github.com/NeuralNetworkVerification/Marabou/files/4584362/marabou-query.zip)

**Comment by kuldeepmeel** [comment]
Hi Andrew:
Thanks for helping us here. One primary question for us is whether we are parsing the returned result from Marabou correctly? 

--
Teodora and Kuldeep

**Comment by anwu1219** [comment]
Hi Teodora and Kuldeep,

> I check the return value of the query as follows:

    sat_vals, stats = MarabouCore.solve(network_query, options=options)

    if stats.hasTimedOut():
        print("TO")
    else:
        if len(sat_vals) == 0:
            print("UNSAT")
        else:
            print("SAT")
Is this the correct way of parsing the returned result when DnC mode is used? I am a bit confused by the worker's results -- I was expecting to see some UNSAT value in one of the worker threads.

You're interpreting the results correctly.
It seems you're running a perception network. Currently we only support DnC with interval splitting, which does not work well with networks with a large input dimension (it could even perform worse than the sequential mode). The workers report timeout because by default we initially give each query a time limit of 5 seconds. That could be too short for the query you're running.

However, we recently introduced some new parallelization techniques for handling perception networks (`https://arxiv.org/abs/2004.08440`). If you're interested in proving properties of your networks, I can share the branch with those techniques with you.

Best regards,
Andrew

**Comment by kuldeepmeel** [comment]
Hi Andrew: 
Yes, we would be very interested in getting access to the optimized version. We are building on top of Marabou, so it would be good to have access to the best version of Marabou. 

Btw, one thing that we observed is that even though all the workers report "TIMEOUT", the value of stats.hasTimedOut() returns False. Perhaps there is a bug in the code? 
Nonetheless, we would be much happier with the most efficient version of Marabou.

**Comment by anwu1219** [comment]
Hi Kuldeep, 
Sorry for getting back to you late. I just sent you an email about the branch containing the new techniques. 
And regarding the return value of DnC, I believe this is indeed a bug. Thanks a lot for bring it up to our attention. I've created a small PR (https://github.com/NeuralNetworkVerification/Marabou/pull/264) to fix that issue. I'll merge it after the travis test passes.
Best wishes,
Andrew

**Comment by anwu1219** [comment]
The bug fix is merged in to the master (as well as the cav20 branch).
