### ISSUE TITLE
CMake runs python tests but does not check for or install required packages

### ISSUE THREAD

**Issue by kjulian3** [NeuralNetworkVerification/Marabou#267]
Python tests were added to CMake in pr #254, but we don't check that the required packages are installed before running the test. Therefore, if a user does not have pytest installed, for example, the build will fail.

**Comment by yuvaljacoby** [comment]
I think this is tricky,
We need to distinguish between two types of users:
* developers  - which I think is better to let them install packages the way they like
* users - which I think should be able to _pip install_, I plan to make that available in the next couple of weeks

So I would not address this issue, @ahmed-irfan @guykatzz @AleksandarZeljic  any thoughts?

**Comment by kjulian3** [comment]
In the mean time, should we set RUN_PYTHON_TEST to OFF as the default in CMake?

We could test maraboupy after building without pytest, and use only nnet format examples, which would let us test maraboupy without needing to install pytest, pytest-cov, codecov, tensorflow, onnx, or onnxruntime. We would still need to install numpy or check that it is installed, but most python users have numpy installed already, and essentially any version of numpy would suffice.

We could also create and run tests using MarabouCore directly, which would avoid the use of numpy, like this example: https://github.com/NeuralNetworkVerification/Marabou/blob/master/maraboupy/examples/MarabouCoreExample.py

**Comment by yuvaljacoby** [comment]
Maybe keep the flag on but change the README to disable the tests (cmake .. -DRUN_PYTHON_TEST=off) ? 
We still run  tests on travis so nothing "bad" can happen .... 

I am trying to think of something that will keep it simple but we will want to fix soon.

**Comment by yuvaljacoby** [comment]
closing this issue,  we have #192 to enable pip install
