### ISSUE TITLE
Marabou doesn't work with TensorFlow 2.0

### ISSUE THREAD

**Issue by syajaman19** [NeuralNetworkVerification/Marabou#272]
When I tried running Marabou with TensorFlow 2.0.0-beta1, the code did not work: 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-18-248f11375c72> in <module>
----> 1 network = Marabou.read_tf("./networks/AutoTaxi.pb")

~/Downloads/Marabou-master/maraboupy/Marabou.py in read_tf(filename, inputNames, outputName, savedModel, savedModelTags)
     50         marabouNetworkTF: (MarabouNetworkTF) representing network
     51     """
---> 52     return MarabouNetworkTF(filename, inputNames, outputName, savedModel, savedModelTags)
     53 
     54 def read_onnx(filename, inputNames=None, outputName=None):

~/Downloads/Marabou-master/maraboupy/MarabouNetworkTF.py in __init__(self, filename, inputNames, outputName, savedModel, savedModelTags)
     44         super().__init__()
     45         self.biasAddRelations = list()
---> 46         self.readFromPb(filename, inputNames, outputName, savedModel, savedModelTags)
     47         self.processBiasAddRelations()
     48 

~/Downloads/Marabou-master/maraboupy/MarabouNetworkTF.py in readFromPb(self, filename, inputNames, outputName, savedModel, savedModelTags)
     88         else:
     89             ### Read protobuf file and begin session ###
---> 90             with tf.gfile.GFile(filename, "rb") as f:
     91                 graph_def = tf.GraphDef()
     92                 graph_def.ParseFromString(f.read())

AttributeError: module 'tensorflow' has no attribute 'gfile'
```

I temporarily downgraded to TensorFlow 1.14.0 and it worked then.

**Comment by grese** [comment]
+1 on this... tensorflow 2.0 support would be great!

**Comment by kjulian3** [comment]
I submitted a pull request with the changes needed to support tensorflow 2.0: #270 

Do those changes solve your issue? If so I think we can get that pr merged in.

**Comment by grese** [comment]
@kjulian3 - I think it should fix the issue I was seeing... Mine was blowing up at the same place as @syajaman19 (`with tf.gfile.GFile(filename, "rb") as f:`).  I'll give it a shot today.

**Comment by grese** [comment]
I downloaded your branch, and I'm still having issues loading a tensorflow v2 saved model after this change.  The screenshot below shows the issue that I'm having.  Think I might be missing something?

<img width="723" alt="Screen Shot 2020-05-27 at 1 40 35 PM" src="https://user-images.githubusercontent.com/4702431/83070245-0adee980-a020-11ea-8dd4-433386eb4072.png">

**Comment by kjulian3** [comment]
One thing you could try is passing ['serve'] to the savedModelTags input when calling Marabou.read_tf:
```
net = Marabou.read_tf('../../scad_tot/artifacts/models/model_v3.2.0/model', savedModel=True, savedModelTags=['serve'])
```
Based on the error message, that seems to be the tag that is available for your model.

However, you may run into new errors, because it looks like tensorflow v2 made a lot of changes to the SavedModel format. Previous testing I'd done used the frozen graph format, but it seems that tensorflow is deprecating frozen graphs in favor of the SavedModel format (https://github.com/tensorflow/tensorflow/releases/tag/v2.0.0)

So if you run into new issues, are you able to share an example SavedModel that I can experiment with?

**Comment by kjulian3** [comment]
I pushed some changes to the pr, so now there's a new option for SavedModel format in tensorflow 2.0 by setting "SavedModel_v2=True". Do these changes allow Marabou to read your network?

**Comment by kjulian3** [comment]
I just merged in a pull request to enable support for tensorflow 2.0 for either the frozen graph format (default) or the SavedModel format. @syajaman19 and @grese, does this solve your issues?

**Comment by grese** [comment]
@kjulian3 - I'll check that out this week and get back you you. Thanks for following up.

**Comment by kjulian3** [comment]
Any updates on this issue? Otherwise I'll assume that the changes I've made to support tensorflow 2.0 are sufficient and close this issue.

**Comment by grese** [comment]
@kjulian3 - Apologies for the delay... this fell off of my radar.  It’s good to go now 👍.  Thanks for your help with this!  Feel free to close the issue.
