### ISSUE TITLE
NLR excessive print statements

### ISSUE THREAD

**Issue by grese** [NeuralNetworkVerification/Marabou#273]
When doing robustness testing, this print statement that gets printed over and over.  Can it be removed or moved to a proper "logger" instead?

https://github.com/NeuralNetworkVerification/Marabou/blob/cf65e39c854005f5b542a4d88b2eb6b539f90d7b/src/engine/Preprocessor.cpp#L46

```
PP: constructing an NLR... successful
PP: constructing an NLR... successful
PP: constructing an NLR... successful
PP: constructing an NLR... successful
PP: constructing an NLR... successful
...
...
```

**Comment by anwu1219** [comment]
Hi, thanks for opening this issue. I've created a PR that addresses this issue.

**Comment by grese** [comment]
Thanks for the speedy turn-around, Andrew :)
