### ISSUE TITLE
The maraboupy directory does not have a Makefile

### ISSUE THREAD

**Issue by wenkokke** [NeuralNetworkVerification/Marabou#307]
The [installation instructions for maraboupy](https://github.com/NeuralNetworkVerification/Marabou/tree/master/maraboupy#installation) say to call `make` from the `maraboupy` directory. However, this directory does not contain a Makefile.

**Comment by wenkokke** [comment]
Looking over the instructions, especially the `-DBUILD_PYTHON=ON` flag, I believe that the README in the maraboupy folder is simply out of date, and the installation instructions should probably just forward to the section on Python in the main README.

**Comment by yuvaljacoby** [comment]
You are absolutely correct, thank you for pointing that out.

PR #311 the issue
