### ISSUE TITLE
Building against local copy of OpenBLAS

### ISSUE THREAD

**Issue by wenkokke** [NeuralNetworkVerification/Marabou#315]
It seems that the [CMake](https://github.com/NeuralNetworkVerification/Marabou/blob/master/CMakeLists.txt#L203-L215) file insists on downloading and compiling OpenBLAS:
```cmake
if (${ENABLE_OPENBLAS} AND NOT MSVC)
    message(STATUS "using openblas for matrix multiplication")
    add_compile_definitions(ENABLE_OPENBLAS)
    #OpenBLAS
    if(NOT EXISTS "${OPENBLAS_DIR}/installed/lib/libopenblas.a")
        execute_process(COMMAND ${TOOLS_DIR}/download_openBLAS.sh)
    endif()

    add_library(${OPENBLAS_LIB} SHARED IMPORTED)
    set_target_properties(${OPENBLAS_LIB} PROPERTIES IMPORTED_LOCATION ${OPENBLAS_DIR}/installed/lib/libopenblas.a)
    list(APPEND LIBS ${OPENBLAS_LIB})
    target_include_directories(${OPENBLAS_LIB} INTERFACE ${OPENBLAS_DIR}/installed/include)
endif()
```
Is it possible to link Marabou against my local copy of OpenBLAS? Or does Marabou require OpenBLAS to be compiled with certain options?

Providing the `OPENBLAS_DIR` on the command-line would be a good solution, but unfortunately it's overwritten, and is suffixed with `/installed` in the script itself.

**Comment by yuvaljacoby** [comment]
Of course, I will do that in a couple of days
