### ISSUE TITLE
Access to set GlobalConfiguration variables from python API

### ISSUE THREAD

**Issue by castrong** [NeuralNetworkVerification/Marabou#339]
I was thinking of adding the ability to set some of the GlobalConfiguration variables from the python API. For example, I would want to be able to set the SPLITTING_HEURISTICS, MILP_SOLVER_BOUND_TIGHTENING_TYPE, and MILPSolverTimeoutValueInSeconds similar to how we can currently set whether to use SBT and whether to use the DnC strategy from the python API. 

**I am looking for feedback on the best way to implement this and whether it would be a good feature to have.** My initial idea is to group these variables with the InputQuery object and then pass this information to the correct objects when the InputQuery is processed in Engine.cpp. I've tried this with the splitting heuristic, where I pass it in and then create a new class variable _divideStrategy + getters/setters for the SmtCore class. The Engine class has access to the query, so it can access the divide strategy directly. If a divide strategy is provided in the InputQuery then it uses that - if not, it uses the GlobalConfiguration variable. Alternatively, more objects could have access to the InputQuery and all of the config variables set from the python API could just be stored there.

**Comment by guykatzz** [comment]
Hi Chris,
This is an interesting idea. So far we assumed that these configuration options are set and never changed, so before exposing each new mutable option we should double check that it doesn't break anything.

Regarding the mechanics of exposing options, I'm not sure logically this belongs with the input query, which encodes the network + property. It makes more sense to me that this interface should belong to the Engine class itself - something like engine.setOption(). What do you think?

**Comment by castrong** [comment]
Yeah, having them in the Engine makes sense to me. They could then be passed in as optional arguments to the [solve function in MarabouNetwork.py](https://github.com/NeuralNetworkVerification/Marabou/blob/90135c707b5b058edf83009798ac4a4e26be8a73/maraboupy/MarabouNetwork.py#L239), which could pass them to the [solve method in MarabouCore.cpp](https://github.com/NeuralNetworkVerification/Marabou/blob/90135c707b5b058edf83009798ac4a4e26be8a73/maraboupy/MarabouCore.cpp#L140) which constructs the Engine object. Alternatively, if we don't want so many optional variables, we could have some sort of Python configuration class which then gets parsed into the right assignments to the Engine object?

**Comment by vbCrLf** [comment]
I'm not sure if it counts as an option, but accessing gurobiEnabled() (from Marabou/src/configuration/Options.h) could be very useful. I would like to make sure Gurobi is enabled in the build I'm running on when starting a heavy task.

**Comment by guykatzz** [comment]
Hi,
I've given this another look. Currently we have two places where parameters are defined: 

1. The GlobalConfiguration file: these are immutable options, set at compilation time.
2. The Options interface: these options have default values but can be modified via command line, the python interface, etc.

There's no real difference between the kinds of options stored in the two places. In particular, it makes sense that the options that you mentioned be moved from GlobalConfiguration to Options. 

The one point that we need to check before moving a value from GlobalConfiguration to Options is that changing this value at various points doesn't break the core. This needs to be checked individually. 

What do you think?

**Comment by idan0610** [comment]
This issue has most likely become stale and is being closed. If there is a requirement to transfer another parameter from GlobalConfiguration to Options, please open a new issue.
