### ISSUE TITLE
Maraboupy - solve() - can't catch an error

### ISSUE THREAD

**Issue by vbCrLf** [NeuralNetworkVerification/Marabou#346]
It is impossible to distinguish UNSAT and Marabou exception when calling `solve()`.
Maraboupy simply returns empty response and statistics (which is the exact case for UNSAT on DNC).
See https://github.com/NeuralNetworkVerification/Marabou/blob/cb7bb66c4958068f56aaf1c3061ee2817846d168/maraboupy/MarabouCore.cpp#L207

I think Maraboupy should check for error or timeout and raise a Python exception in response to that.

**Comment by anwu1219** [comment]
Issue closed with merging of PR https://github.com/NeuralNetworkVerification/Marabou/pull/511
