### ISSUE TITLE
getTotalTime() in Statistics.cpp doesn't include _preprocessingTime

### ISSUE THREAD

**Issue by castrong** [NeuralNetworkVerification/Marabou#350]
Currently it seems that the totalTime() returned by Statistics doesn't include the preprocessing time. This means that preprocessing time won't be factored into timeouts. Currently if I run a query with a 5 second timeout, it will preprocess for 10 seconds, then run the main loop for ~5 seconds, then time out. Is this desired behavior (should the timeout refer to the main loop time or the main loop + preprocessing time). If not, getTotalTime() could include the preprocessing time.

I think ideally we would also be able to timeout within the preprocessing, especially for cases where preprocessing could take a very long time (say if bound tightening is done with a MIP formulation). In order to enable timing out during the preprocessing, a timeout check like in the Engine.cpp function solve() could be added to void Engine::performMILPSolverBoundedTightening()(see below).

```
            if ( shouldExitDueToTimeout( timeoutInSeconds ) )
            {
                if ( _verbosity > 0 )
                {
                    printf( "\n\nEngine: quitting due to timeout...\n\n" );
                    printf( "Final statistics:\n" );
                    _statistics.print();
                }

                _exitCode = Engine::TIMEOUT;
                _statistics.timeout();
                return
            }
```

It would need some way to access the timeoutInSeconds during the preprocessing.

**Comment by anwu1219** [comment]
Now it returns the actual time that has passed.
