### ISSUE TITLE
Illegal properties parsed by property parser

### ISSUE THREAD

**Issue by alexopenu** [NeuralNetworkVerification/Marabou#372]
I've noticed that the syntax of indices of variables in property files is not checked very much; normally everything that comes after digits is simply ignored, and if there are no digits in the beginning of the index, the whole line seems to be ignored. 

So for example:

y1-1 >= 0 is parsed as y1 >= 0
y-1 >= 0 seems to get simply ignored

This is not the case with parsing the scalars. 

I attach an example of a corrupt property file that gets parsed, and (not that this is necessary) a script the parses it, prints the resulted bounds on variables, and solves the resulted query. Everything works, and there is no indication that there was any issue along the way. This can be an issue if the property is automatically created, and there is no strict syntax checking on the side of the user that verifies that it is legal. This way the user may get UNSAT to a corrupt query without realizing that there was a problem. 

Perhaps it would be better to throw an exception if a corrupt index of a variable is provided?

[bad_property_example.txt](https://github.com/NeuralNetworkVerification/Marabou/files/5210864/bad_property_example.txt)

[corrupt_property_example.py.txt](https://github.com/NeuralNetworkVerification/Marabou/files/5210832/corrupt_property_example.py.txt)

**Comment by idan0610** [comment]
This issue has most likely become stale and is being closed. If the problem persists, please contact us or open a new issue.
