### ISSUE TITLE
Installation issue - OpenBLAS imported target "openblas" includes non-existent path

### ISSUE THREAD

**Issue by grese** [NeuralNetworkVerification/Marabou#380]
There seems to be an issue on latest OS X during a fresh install.. I ran the following commands:  

* `git clone https://github.com/NeuralNetworkVerification/Marabou.git`
* `mkdir Marabou/build && cd Marabou/build`
* `cmake .. -DBUILD_PYTHON=ON`

The cmake command above fails with several errors about “Imported target "openblas" includes non-existent path”.  They all look like the error below.

```
CMake Error in CMakeLists.txt:
  Imported target "openblas" includes non-existent path

    "/Users/me/Projects/Marabou/tools/OpenBLAS-0.3.9/installed/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

OS version: OS X 10.15.6
cmake version: 3.16.4

_Some additional information:_ Running the following commands can be used as a workaround to get past the error, however the same error will happen again when doing a fresh install.
1. Remove Open-BLAS: `rm -rf ../tools/OpenBLAS-0.3.9`
2. Re-run `cmake .. -DBUILD_PYTHON=ON`

**Comment by shrutilimaye** [comment]
Recently I came across same issue. The main problem is with OPENBLAS include folder.There is no data / files in the path "installed/include/ ". When you try the command " cmake .. -DBUILD_PYTHON=ON " , OPENBLAS does not get installed correctly thus you cant trace / include folder anywhere. 

I found a solution to this,
1. I downloaded OPENBLAS library from its official site and renamed it as  " OpenBLAS-0.3.9 " inside Marabou-master/tools/.
2. Open OPENBLAS readme.txt and install it using given steps. It gets properly installed and you can spot the include folder. 
   ( Make sure to give the target path while installing the OPENBLAS in the linux terminal - google the syntax).
3. When its properly installed  , find "libopenblas.dll.a" and transfer to "Marabou-master/tools/OpenBLAS-0.3.9/lib/
4. Open CMakeLists.txt inside "Marabou-master/" and change lines as follows : 


if (NOT MSVC)
if (${ENABLE_OPENBLAS})
    message(STATUS "using openblas for matrix multiplication")
    add_compile_definitions(ENABLE_OPENBLAS)
    #OpenBLAS
    if(NOT EXISTS "${OPENBLAS_DIR}/lib/libopenblas.dll.a")
        message("Can't find open blas, installing. If open blas is isntalled please use the OPENBLAS_DIR parameter to pass the path")
        if (${OPENBLAS_DIR} STREQUAL ${OPENBLAS_DEFAULT_DIR})
            message("installing openblas")
            execute_process(COMMAND ${TOOLS_DIR}/download_openBLAS.sh)
        else()
            message(FATAL_ERROR "Can't find openblas in the supplied directory")
        endif()
    endif()

    add_library(${OPENBLAS_LIB} SHARED IMPORTED)
    set_target_properties(${OPENBLAS_LIB} PROPERTIES IMPORTED_LOCATION ${OPENBLAS_DIR}/lib/libopenblas.dll.a)
    list(APPEND LIBS ${OPENBLAS_LIB})
    target_include_directories(${OPENBLAS_LIB} INTERFACE ${OPENBLAS_DIR}/include)
endif()
endif()


YOU ARE GOOD TO GO !  (I hope the description is detailed - it took me almost 2 days to figure out and install Marabou)

- Current student as USC 
- MS in Electrical Engineering (VLSI)
Shruti Limaye

**Comment by grese** [comment]
Hey guys, I noticed something during the build on MacOS that may help resolve this issue.  Here's an error that shows up while trying to compile OpenBLAS:

```

**Comment by anwu1219** [comment]
issue should be cleared with recent update in MacOS build and OpenBLAS version, which are merged in the master.
