### ISSUE TITLE
pip package?

### ISSUE THREAD

**Issue by grese** [NeuralNetworkVerification/Marabou#388]
# pip package?
Publishing Marabou as a PyPI package would be nice because `pip install marabou` would be much quicker and easier than compiling for people not actively developing the project. The process should be relatively simple, but may require some procedural changes with how you manage releases. From what I've seen in the repo, you're most of the way there already because you already have a API documentation and a travis build.

**Here's the basic outline of what would need to be done (I might be missing a couple of minor steps):**
1. [Register](https://pypi.org/account/register/) the package name (e.g. “marabou") with [PyPI](https://pypi.org)
2. [Package](https://packaging.python.org/tutorials/packaging-projects/) the project
3. Use [semver](https://semver.org) versioning (e.g. v1.0.1) for your [Github releases](https://github.com/NeuralNetworkVerification/Marabou/releases)
4. Setup the travis build to publish to PyPI using [twine](https://pypi.org/project/twine/) when a new version is released.

**Resources for packaging & publishing Python packages**

_Packaging Tutorial:_
[Python packaging tutorial](https://packaging.python.org/tutorials/packaging-projects/)

_Packaging User Guide:_
[Python Packaging User Guide](https://packaging.python.org)

_Another tutorial:_
[How to Publish an Open-Source Python Package to PyPI](https://realpython.com/pypi-publish-python-package/)

**Comment by grese** [comment]
Hey everyone, if there's any interest in this, I'd be willing to put in the effort to package it. After setting everything up, I could just transfer ownership of the PyPI package over to one of the core maintainers of marabou. Let me know if you'd like me to start on it.

**Comment by guykatzz** [comment]
Hi John,
That would be awesome! By all means, go ahead :).

**Comment by grese** [comment]
@guykatzz - Is [COPYING](https://github.com/NeuralNetworkVerification/Marabou/blob/master/COPYING) the license you'd like to use?

**Comment by guykatzz** [comment]
Yes, thanks!

**Comment by grese** [comment]
@guykatzz - I'm finally circling back to this task after the holidays, and I have a few questions...

1. Currently, the travis build compiles for Windows and Linux. To support MacOS, I believe an 'osx' job will need to be added to the travis build. Agreed?
2. Does Marabou have any specific OS version requirements for Windows/Mac/Linux?
3. Do the binaries from the travis build get published/stored anywhere after testing? It doesn't look like it from the travis build, but I thought I'd double-check. This is something we'll need because the binaries will need to be included in (or downloaded by) the pip package.

**Comment by grese** [comment]
My current plan is to setup a separate GitHub Action called "release" which can be run independently from the CI build. When the Marabou team wants to release a new version of Marabou (and the pip package), they can just manually trigger this release action. Below is a summary of what this "release" action will do...

1. Run tests, and build static binaries for Linux, Windows, and MacOS.
2. Create the pip package & run a simple "import" test.
3. Increment the version number and create a new ["Release Tag"](https://github.com/NeuralNetworkVerification/Marabou/tags) for the new version.
4. Upload the static binaries as ["release assets"](https://github.com/actions/upload-release-asset), which would be tied to the new release tag.
5. Publish the new version of the pip package to PyPI.

When a user installs the pip package, the "setup.py" script will be called (which is a standard part of the setup process for pip packages). In our case, the "setup.py" script will download the correct static binary from the "release assets" for the particular OS and release tag.

_A quick note..._
Currently, the "CI" action only runs on Ubuntu. To prevent any surprises in the "release" job, I was thinking that it might be nice to update the CI job to build/test on Linux, Windows, and MacOS on each "pull_request" and "push". If we do that, we wouldn't necessarily have to run the tests during the "release" because they would have already been run during the last CI build. Doing this would also help catch any cross-platform issues sooner rather than later. So, if we adopt this approach, step 1 would only have to build the 3 static binaries instead of building and testing.

**Comment by guykatzz** [comment]
Hi John,
Again, many thanks for working on this.

Adding Aleks @AleksandarZeljic and Clark @barrettcw to the discussion. 

The steps you outlines in your second message make sense. 

Indeed, we've moved away from Travis due to various limitations, and are now using GitHub Actions. Also, we've suspended support for Windows for now - we don't have anyone on the team who's a Windows expert, and the overhead became too great. 

Adding an OSX build makes sense.

I don't think we have version requirements for the operating systems. We do have package requirements that you mentioned.

I think going for a static binary makes sense. 

Aleks, Clark, do you have any comments?

**Comment by grese** [comment]
@guykatzz - Thanks for the response. I've got the basic pieces put together, and now I'm just working on stitching everything together. I should have a test version published to the PyPiTest  (the "test" repository) repository soon.

**Comment by grese** [comment]
@guykatzz, @AleksandarZeljic, @barrettcw - Another quick question... The project is compiled using two different compilers (g++ and clang++). Just curious... Why not choose one? Is this a common thing with c++ projects?

**Comment by grese** [comment]
I ran into a little snag... I don't think the static linking is going to work on MacOS. So, we may have to just use dynamically linked libraries. Was anybody else able to get static linking to work on MacOS?

**Comment by barrettcw** [comment]
One note that might be relevant - in another project, we discovered that we could statically link all of the libraries on MacOS, but the final link to form the binary has to be dynamic because MacOS doesn't have a static libc or something like that.  But this still works pretty well - you can distribute the resulting binary and it works on other MacOS systems.

**Comment by idan0610** [comment]
Marabou can be installed via pip now, so this issue is closed.
