### ISSUE TITLE
Use LP Relaxation - Gurobi with python

### ISSUE THREAD

**Issue by preritt** [NeuralNetworkVerification/Marabou#389]
Hi 

Are there examples illustrating the use of Gurobi with Python using Marabou or is it supported only with C++?  

Thanks

**Comment by anwu1219** [comment]
Hi, if Gurobi is set up on your machine and you have built Marabou with cmake option `-DENABLE_GUROBI=ON`,
the LP preprocessing should be turned on by default whether you're using python or C++.
If you'd like to share an example I'm happy to check for you whether LP preprocessing is running correctly on that example.

**Comment by preritt** [comment]
Hi Andrew,
Thanks for your reply - sorry, I just saw your response. 
I was able to successfully use `Marabou` without Gurobi. I was just curious, if the build was without Gurobi - what kind of optimization is used.

I used the following code snippet that worked:
```
        options = Marabou.createOptions(numWorkers= 12,initialTimeout=10,
                                        onlineDivides=8, timeoutInSeconds=20,
                                        timeoutFactor=2,
                                        snc=True, verbosity=0, initialDivides=8)
        vals1, stats1 = net1.solve(options=options)
```
Thanks!

**Comment by anwu1219** [comment]
Hi if the build was without gurobi, then Symbolic bound propagation is used to preprocess the query and also interleaved with the search.
The only comment I had with the command you had is that since intialDivides and onlineDivides are the number of bisections. Setting it to 8 would lead to 64 subproblems. Instead you might want to set those numbers to be 3.

**Comment by preritt** [comment]
Hi 
Thanks for your feedback. I can try that.
However, these setting worked for multiple experiments that I have done. Is there any harm with 64 sub problems?

I assume setting to 3 would give 9 sub problems.

**Comment by anwu1219** [comment]
Hi,

setting to 3 would give 2^3 = 8 subproblems. 
Online divides of 8 means that whenver a sub-query times out, that sub-query is split into 64 sub-queries to be solved. That might be too overwhelming for 12 cores and might not give the best solver performance.

**Comment by preritt** [comment]
Hi,

Thanks again. I can try doing that. However, these setting worked well for me. I am using dedicated cluster, so maybe all job that the processor does is this program with nothing running in the background.

**Comment by preritt** [comment]
Hi,
Is there a way to timeout the solver during computation. For instance if we can't find a solution within 50s, I would like the solver to indicate the solution is infeasible. For some larger NNs, I found that the solver gets stuck. Is there a place to specify this timeout parameter?

Thanks!

**Comment by anwu1219** [comment]
Hi,

Yeah, one can set the timeoutInSeconds option (https://github.com/NeuralNetworkVerification/Marabou/blob/10f953a97a8748abbbc51524757bbedd2a0e4026/maraboupy/Marabou.py#L155), 
which specifies the timeout in seconds. The program might be terminated in a little longer than the specified timeout, since the program checks for timeout only periodically. 

Btw, if you have access to Gurobi, to get good performance on larger networks, it is recommended to set MILPTightening="none", and solveWithMILP="True".
https://github.com/NeuralNetworkVerification/Marabou/blob/10f953a97a8748abbbc51524757bbedd2a0e4026/maraboupy/Marabou.py#L167

**Comment by preritt** [comment]
Thanks for your quick reply!
I will try these and see how it goes.

**Comment by preritt** [comment]
Hi
I tried installing with Gurobi. However, I am not sure if the installation was successful. Is there a way to check if Gurobi has actually been enabled. 
I used the following setup:
`  options = Marabou.createOptions(numWorkers= 12,initialTimeout=10,
                                  onlineDivides=3, timeoutInSeconds=20,
                                  timeoutFactor=2,
                                  snc=True, verbosity=0, initialDivides=3, solveWithMILP = True)    
`

However, on running I got the following error:

`TypeError: createOptions() got an unexpected keyword argument 'solveWithMILP'`


Thanks.

**Comment by alexopenu** [comment]
Hi,

In regard to installation with gurobi, make sure that the
flag ENABLE_GUROBI is ON here
<https://github.com/NeuralNetworkVerification/Marabou/blob/master/CMakeLists.txt#L15>

Note that if gurobi is enabled, you will get this
<https://github.com/NeuralNetworkVerification/Marabou/blob/master/CMakeLists.txt#L192>
message during compilation: "Using Gurobi for LP relaxation for bound
tightening".

You should also see messages regarding gurobi-related tests.

In regard to MILP timeout, note that if you update to the latest version,
there should be a new argument
<https://github.com/NeuralNetworkVerification/Marabou/blob/master/maraboupy/Marabou.py#L169>
milpSolverTimeout,
which is the milp solver timeout per neuron [e.g., set to t seconds, the
process should terminate in more or less t*(number of neurons in your
network) ].

Hope this helps.
Alex

**Comment by preritt** [comment]
Hi Alex,
Thanks for getting back. I will install the latest version and get back if I run into issues.
