### ISSUE TITLE
Verify MNIST with Marabou

### ISSUE THREAD

**Issue by AvrahamRaviv** [NeuralNetworkVerification/Marabou#390]
Hi
Has anyone tried to verify MNIST with Marabou?
(something like: https://github.com/sisl/NeuralVerification.jl/blob/master/examples/cars_workshop/5%20image%20classification.ipynb)

**Comment by guykatzz** [comment]
Hi Avraham,
The repository actually comes with a bunch of MNIST models you can play with. Have a look at 

https://github.com/NeuralNetworkVerification/Marabou/tree/master/resources/nnet/mnist

These examples can be run through the command line, or you could load them from the Python interface. There are also properties that you can test on these networks, under

https://github.com/NeuralNetworkVerification/Marabou/tree/master/resources/properties/mnist

**Comment by AvrahamRaviv** [comment]
Thanks!
