### ISSUE TITLE
Compatibility issues between tensorflow 2.3 and maraboupy

### ISSUE THREAD

**Issue by idan0610** [NeuralNetworkVerification/Marabou#393]
It seems there are some compatiblity issues between tensorflow 2 and maraboupy.
In this example code attached, I try to save a tensorflow keras model with the name "verification_model", but instead of creating a folder named "verification_model" with the model files inside, a single file called "verification_model" is created. After that, maraboupy failed to parse the model, with the error:

> Traceback (most recent call last):
>   File "C:/Users/Idan/Desktop/study/thesa/toy_example.py", line 39, in <module>
>     res = marabou_example()
>   File "C:/Users/Idan/Desktop/study/thesa/toy_example.py", line 18, in marabou_example
>     network = Marabou.read_tf("verification_model", modelType="savedModel_v2")
>   File "D:\Marabou\maraboupy\Marabou.py", line 62, in read_tf
>     return MarabouNetworkTF(filename, inputNames, outputName, modelType, savedModelTags)
>   File "D:\Marabou\maraboupy\MarabouNetworkTF.py", line 54, in __init__
>     self.readTF(filename, inputNames, outputName, modelType, savedModelTags)
>   File "D:\Marabou\maraboupy\MarabouNetworkTF.py", line 112, in readTF
>     loaded = tf.saved_model.load(filename)
>   File "D:\Python\Python37\lib\site-packages\tensorflow\python\saved_model\load.py", line 603, in load
>     return load_internal(export_dir, tags, options)
>   File "D:\Python\Python37\lib\site-packages\tensorflow\python\saved_model\load.py", line 614, in load_internal
>     loader_impl.parse_saved_model_with_debug_info(export_dir))
>   File "D:\Python\Python37\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 56, in parse_saved_model_with_debug_info
>     saved_model = _parse_saved_model(export_dir)
>   File "D:\Python\Python37\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 113, in parse_saved_model
>     constants.SAVED_MODEL_FILENAME_PB))
> OSError: SavedModel file does not exist at: verification_model/{saved_model.pbtxt|saved_model.pb}

If I remove the import to maraboupy from the file, tensorflow is able to save the model properly, but then I can't use maraboupy on the same file.

My example code (attached as a file):

```
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from maraboupy import Marabou


def marabou_example():
    verification_model = keras.Sequential()
    verification_model.add(layers.Dense(2, activation="relu", input_shape=(4,)))
    verification_model.add(layers.Dense(2, use_bias=False))
    verification_model.compile()

    verification_model.set_weights(
        [np.array([[3, 0], [0, 3], [4, 0], [0, 4]]), np.array([-5, 2]), np.array([[1, -1], [-1, 1]])])
    tf.keras.models.save_model(verification_model, "verification_model")

    network = Marabou.read_tf("verification_model", modelType="savedModel_v2")
    input_vars = network.inputVars[0][0]
    output_vars = network.outputVars[0]

    network.setLowerBound(input_vars[0], -0.5)
    network.setUpperBound(input_vars[0], 0.5)
    network.setLowerBound(input_vars[1], -0.5)
    network.setUpperBound(input_vars[1], 0.5)
    network.setLowerBound(input_vars[2], -0.5)
    network.setUpperBound(input_vars[2], 0.5)
    network.setLowerBound(input_vars[3], -0.5)
    network.setUpperBound(input_vars[3], 0.5)

    network.addInequality(output_vars, [-1, 1], 0)

    res = network.solve()

    return res


if __name__ == '__main__':
    res = marabou_example()
```

Checked on Windows 10 and Debian GNU/Linux 10 (HUJI CS labs environment), both with tensorflow 2.3.0.

[toy_example.zip](https://github.com/NeuralNetworkVerification/Marabou/files/5434285/toy_example.zip)

**Comment by wu-haoze** [comment]
The teat_requirement file specify the tensorflow version we support. 
 https://github.com/NeuralNetworkVerification/Marabou/blob/20a5d070dc95626014908823f411d3901229937c/maraboupy/test_requirements.txt#L9
