### ISSUE TITLE
ImportError: No module named MarabouCore

### ISSUE THREAD

**Issue by lebohnes** [NeuralNetworkVerification/Marabou#401]
Hallo together,

After following the Installation Guide from [the documentation](https://neuralnetworkverification.github.io/Marabou/) I always get the following Error:
```
Exception has occurred: ModuleNotFoundError
No module named 'maraboupy.MarabouCore'
  File "/home/user/docs/Marabou/maraboupy/Marabou.py", line 17, in <module>
    from maraboupy.MarabouCore import *
  File "/home/user/docs/Marabou/1_TensorflowExample.py", line 16, in <module>
    from maraboupy import Marabou
```

The marabou repository was before added to the pythonpath. Also the file "MarabouCore.cpython-36m-x86_64-linux-gnu.so" was successfully been created during the build. The usage of different python versions didn't solved the issue. Every test had the same issue as mentioned above. 

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic

```
Thanks alot!
Greets

**Comment by alexopenu** [comment]
Hello

One possible issue may be that the Marabou directory is not in your python path. Try to add the following lines in the beginning of your python script:

import sys
sys.path.append(MARABOU_DIR)

where MARABOU_DIR is the path to your Marabou directory, e.g. '/Users/username/my_projects/Marabou'

**Comment by lebohnes** [comment]
Thank you very much.

I added it in 3 different ways to the PYPATH:

1. globally in ubuntu (export PYTHONPATH=$PYTHONPATH:/Users/username/my_projects/Marabou
2. added it in Visual Studio Code to the "settings.json"
3. tried the option you discribed

Sadly it still gave me the error.

Also if i debug the python file it jumps inside the 'Marabou.py' file to the statement in line 17:
`from maraboupy.MarabouCore import *` and throws there the ModuleNotFoundError Exception. I think if the problem is the missing directory to pypath it shouldn't jump in the "Marabou.py". 

Also i redownloaded and rebuilded the project 4 times and always got the same error again.

Thanks alot!
Greets

**Comment by lebohnes** [comment]
Tried it out in a Virtual Machine and it works there. I will set up a new OS and will retry it. This is no global issue.
