### ISSUE TITLE
Memory-leak potential

### ISSUE THREAD

**Issue by vbCrLf** [NeuralNetworkVerification/Marabou#406]
`Tableau::storeState` will memory-leak if the parameter `state` is already initialized (because `state.setDimensions` will reallocate the memory w/o freeing the old memory).
I went over all code paths to this function (I think) and it always gets called on uninitialized state, so in practice there is no memory-leak. But I can see how a leak can be easily introduced by mistake in the future, so it might worth changing.
@AleksandarZeljic

**Comment by guykatzz** [comment]
Hi Aleks,
I asked Ori to tag you because I imagine this is stuff that will soon be changed anyway as part of your PRs. If so, and seeing as there's no bug at present, perhaps we can ignore this for now.

**Comment by AleksandarZeljic** [comment]
Thanks for the ping! Yeah, we will get rid of this code entirely. Currently on my experimental branch the split-and-conquer mode still uses this, but Andrew and I came up with a scheme that should avoid it altogether. So I don't think this will be an issue in the future.
