### ISSUE TITLE
Disable all the Marabou outputs?

### ISSUE THREAD

**Issue by EmanueleLM** [NeuralNetworkVerification/Marabou#409]
Hi,

after reading the documentation, I couldn't find an easy way to disable all the console outputs from marabou solver (python API). 
Is there a snippet of code that I can add to prevent Marabou from outputting all the details of the verification phase?
I'm not interested in re-directing output to another file: I'm trying to push the performances to the limit.

Sorry I forgot to say: I set `verbose` variable in Marabou.py, createOptions to 0 (default 2), but it doesn't affect the verbosity of the output.

Thank you,
Emanuele

**Comment by AleksandarZeljic** [comment]
Hi Emanuele, is this still an issue?
