### ISSUE TITLE
MILP bound tightening weird behaviour

### ISSUE THREAD

**Issue by vbCrLf** [NeuralNetworkVerification/Marabou#417]
I ran a queries on a few ACASXU networks with MILP bound tightening, and used `_tableau->dumpAssignment()` to examine the resultant bounds immediately after the preprocessing. I noticed some very weird bounds, which I thought might hint at an issue with the MILP implementation.
The queries I ran were simply the ACASXU networks with a smaller input range. The phenomenon I saw is that some ReLU forward variables upper bounds were much higher than their's backward variable's upper bounds. For example, for ACASXU v2a 1,1 I got:
```
	x369 (index: 232)  -->  2.08643 [B]. Range: [ 0.33647, 11.21769 ] 
	x370 (index: 187)  -->  0.33647 [NB]. Range: [ 0.33647, 202.77663 ] 
```
and for v2a 5,7 I got:
```
	x351 (index: 223)  -->  0.80104 [B]. Range: [ 8.73128, 247.08718 ] *
	x352 (index: 178)  -->  8.73128 [NB]. Range: [ 8.73128, 5936.06544 ] 
```
In both examples the difference between the backward and forward variable is very high. I ran it with MILP timeout of 60 seconds.

I'm not sure if it is really an issue.

The two full outputs:
[acasxu_experimental_v2a_1_1.txt](https://github.com/NeuralNetworkVerification/Marabou/files/5754087/acasxu_experimental_v2a_1_1.txt)
[acasxu_experimental_v2a_5_7.txt](https://github.com/NeuralNetworkVerification/Marabou/files/5754088/acasxu_experimental_v2a_5_7.txt)
The phenomenon appears on every ACASXU network I ran on.

**Comment by guyam2** [comment]
assigned.

**Comment by idan0610** [comment]
We were unable to reproduce the issue in the latest version of Marabou.
This issue has most likely become stale and is being closed.  If the problem persists, please contact us or open a new issue.
