### ISSUE TITLE
ACAS Xu Lookup Table Data

### ISSUE THREAD

**Issue by kgoyal40** [NeuralNetworkVerification/Marabou#419]
Hi, 

Is the look up table data for ACAS Xu is publicly available somewhere?

Thanks!

**Comment by mykelk** [comment]
The network in the original Reluplex paper was trained on an extremely early prototype from several years ago. The real version of ACAS Xu recently became standardized as RTCA DO-386 (it is based on a lookup table, not a neural network). The standard may be obtained from the [RTCA standards organization](https://www.rtca.org/standards/). If your aim is to test your verification tools and you want to train your own collision avoidance networks, then you might be interested in some non-ACAS tables. They are purely notional and only very loosely inspired by ACAS X, but it should be adequate for testing general purpose verification tools.
https://github.com/sisl/HorizontalCAS
https://github.com/sisl/VerticalCAS
