### ISSUE TITLE
Syntax errors while building on Windows

### ISSUE THREAD

**Issue by Omniscimus** [NeuralNetworkVerification/Marabou#433]
Hello, I am trying to use Marabou in my thesis. When I try to build Marabou on Windows using Visual Studio, the build fails with a long list of errors, such as:
```
  c:\program files (x86)\windows kits\10\include\10.0.19041.0\um\rpcnsip.h(71): error C2446: ':': no conversion from 'C
VC4::MessageC' to 'CVC4::NullC' [C:\Users\Omni\Downloads\Marabou\build\MarabouHelperTest.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.19041.0\um\rpcnsip.h(71): error C2491: 'I_RpcReBindBuffer': defin
ition of dllimport data not allowed [C:\Users\Omni\Downloads\Marabou\build\MarabouHelperTest.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.19041.0\um\winscard.h(1255): error C2061: syntax error: identifie
r 'UUID' [C:\Users\Omni\Downloads\Marabou\build\MarabouHelperTest.vcxproj]
```
The full output can be found [here](https://gist.github.com/Omniscimus/0bba8b2a45ec11645f73157585a9c710).

I followed the following steps:
1. I installed Visual Studio 2017 with the Desktop Development C++ item. All following commands are executed in a VS 2017 Developer Command Prompt.
2. 
```
cd path\to\marabou\repo\folder
mkdir build 
cd build
cmake .. -G"Visual Studio 15 2017 Win64"
```
So far, everything seems to go fine.
3.
`cmake --build . --config Release`
This generates a lot of errors and warnings. It looks like the errors are all in the `C:\Program Files (x86)\windows kits\` directory.

Does anyone know how to fix this?

**Comment by AleksandarZeljic** [comment]
Hi, unfortunately we are currently stepping away from supporting Windows at this point in time. The commit  [0fc1d10](https://github.com/NeuralNetworkVerification/Marabou/commit/0fc1d10ff0e1859cf32abe54eb22f3ec0fec59f) from January 31st should compile on Windows, can you give it a try?

**Comment by Omniscimus** [comment]
Thanks for your reply, I will try that. Are you also stopping development for MacOS or will both Mac and Linux remain fully working?

**Comment by Omniscimus** [comment]
> Hi, unfortunately we are currently stepping away from supporting Windows at this point in time. The commit [0fc1d10](https://github.com/NeuralNetworkVerification/Marabou/commit/0fc1d10ff0e1859cf32abe54eb22f3ec0fec59f) from January 31st should compile on Windows, can you give it a try?

Building 0fc1d10 indeed results in a working Marabou executable at `build\Release\Marabou.exe.exe`, although during the build process I get errors from the tests:
```
  Generating Test_AbsoluteValue.cc
    File "C:/Users/Omni/Downloads/Marabou/tools/cxxtest/cxxtestgen.py", line 60
      print usageString()
            ^
  SyntaxError: invalid syntax
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209
,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Users\Omni\Downloads\Marabou\build\src\system_tests\Test_Abso
luteValue.exe.vcxproj]
```
I tested this with both Python 3 and 2. Both give this error. But the main Marabou executable compiles as expected.

**Comment by AleksandarZeljic** [comment]
Our CI workflow has only Linux at this point since we do not have any members who use Windows/MacOS platforms primarily. Windows build is not going to work until we invest some effort into it, the MacOS build should be fine, but we do not have a CI workflow for it.   

Regarding cxxtestgen.py, this seems to be related to external, based on a quick Google search. Can you try to run that particular script from the command line?

**Comment by Omniscimus** [comment]
When using the command line, I indeed only get this error with cxxtestgen.py when using Python 3, not when using Python 2. So maybe it has something to do with my setup. During the build process, I set the python executable in the first cmake command:
```
cmake .. -G"Visual Studio 15 2017 Win64" -DPYTHON_EXECUTABLE="C:\Users\Omni\Anaconda3\envs\MyEnv\python.exe"
```

**Comment by AleksandarZeljic** [comment]
Does that fix the issue or does it persist even when you set the Python executable explicitly?

**Comment by Omniscimus** [comment]
I also got that error when setting the Python executable explicitly. But I have now installed Linux (wsl) and it works perfectly 👍

**Comment by AleksandarZeljic** [comment]
Great to hear that you have a workaround, I will take note of this behavior for the future and close the issue. Thanks for your feedback and hope you'll have a good time using Marabou.
