### ISSUE TITLE
Does marabou support two output variables?

### ISSUE THREAD

**Issue by LebronX** [NeuralNetworkVerification/Marabou#447]
Hi,

Does marabou support two output variables? Or is there some way to hack in the code to make it support two output variables?

Thanks

**Comment by anwu1219** [comment]
Hi, 

Marabou does support multiple output variables.

The readme contains guide to using Marabou on the command line.
This folder contains some examples of using Marabou's Python API:
https://github.com/NeuralNetworkVerification/Marabou/tree/master/maraboupy/examples

Haoze

**Comment by LebronX** [comment]
Hi,

Thanks for the prompt answer!

I am trying to use Marabou's Python API to read .onnx file. The network has two output variables. And when I read it, it gives error:

RuntimeError: Your model has multiple outputs defined
Please specify the name of the output you want to consider using the 'outputName' argument

Or maybe marabou only support multiple output variables for .nnet file?

Thanks

**Comment by anwu1219** [comment]
Hi,

Yeah, so right now the onnx parser only support networks with 1 output **node**, which can be a vector of variables (e.g., in the case of MNIST). But it doesn't support multiple output nodes. 
Is it possible to create the network such that it only contains 1 output node?
We could potentially support multiple output node by extending this file:
https://github.com/NeuralNetworkVerification/Marabou/blob/master/maraboupy/MarabouNetworkONNX.py

Also, if your property only concerns one of the output node, you could specify that by setting the outputName argument.
`readONNX(filename, outputName={node_name}) `


Andrew

Andrew

Andrew

Andrew

**Comment by LebronX** [comment]
My two output nodes are of multiple different data types and my property also involves multiple output nodes. Maybe it is better to extend the file you mention.

Thanks!
