### ISSUE TITLE
TinyTaxi dataset

### ISSUE THREAD

**Issue by LebronX** [NeuralNetworkVerification/Marabou#449]
Hi,

I would like to know where is the tinytaxi dataset that you used to evaluate in FMCAD paper. I couldn't find it in this repository or the artifact you provide.

Thanks

**Comment by anwu1219** [comment]
Hi,
Please find attached the benchmarks we used for taxi net. The folder contains the two networks and the properties used in the evaluation. Please let me know if you have trouble running the benchmarks.
[taxi_benchmarks.zip](https://github.com/NeuralNetworkVerification/Marabou/files/6359986/taxi_benchmarks.zip)

Andrew

**Comment by LebronX** [comment]
Hi,

Thanks for the prompt reply! However, I would like to ask for the data of tinytaxi but not the networks or properties.

Thanks

**Comment by anwu1219** [comment]
Hi, sorry for the late response. Yes, you can access the training data here:

https://drive.google.com/drive/folders/1QmiDXuvovNQn7nsQsvhdodRBv1_V8iQF

**Comment by LebronX** [comment]
Hi, Thank you very much for the answer!
