### ISSUE TITLE
bug with SNC printed output

### ISSUE THREAD

**Issue by guyam2** [NeuralNetworkVerification/Marabou#450]
Hi @anwu1219 

I think there is a problem with the **printed output** of running in SNC mode in case the input query is SAT.

I noticed that for the attached input query:
[sat_k_1_dt_0.3_edited.txt](https://github.com/NeuralNetworkVerification/Marabou/files/6391558/sat_k_1_dt_0.3_edited.txt)

I get infeasible outputs when running **WITH** SNC mode.
For example, for the attached (SAT) query I have a constraint that **output_0 (var # 48)>= output_i for 1<=i<=5 (vars # 49- 53)**.

When running Marabou on the input query **WITHOUT** SNC I got that the query is SAT and that the satisfying assignment brings the following output:

![good_output](https://user-images.githubusercontent.com/60099459/116398997-1985e000-a831-11eb-93f1-bc3111e12673.png)

Which seems correct, and indeed complies with the required constraints encoded in the input query (the first output variable has the largest value).

But on the other hand, when running Marabou on the input query **WITHOUT** SNC mode - I still get SAT (which is correct) but the output presented does not comply with the constraints:

![bad_output](https://user-images.githubusercontent.com/60099459/116399122-41754380-a831-11eb-9be0-3a482a860105.png)

From my understanding, the bottom line is that - _SNC mode gives a correct SAT / UNSAT result, and also a correct assignment for the inputs - but presents incorrect outputs for the satisfying input assignment_.

What do you think?

Thanks for the help!

**Comment by idan0610** [comment]
It seems that this bug no longer exists in the latest version, so this issue is closed.
