### ISSUE TITLE
Error installation MAC

### ISSUE THREAD

**Issue by mducoffe** [NeuralNetworkVerification/Marabou#459]
Hy everyone, 

we would like to test maraboupy on mac.
going thought the installation set up we encounter the following error with the cmake:
"""
Can't find open blas, installing. If open blas is isntalled please use the OPENBLAS_DIR parameter to pass the path
installing openblas
Downloding openBLAS
Unzipping openBLAS
Installing openBLAS
getarch.c:80:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
make: *** [getarch] Error 1
Makefile.system:220: Makefile.conf: No such file or directory
Makefile.system:1134: Makefile.: No such file or directory
make: *** No rule to make target `Makefile.'.
"""
Would you have any suggestion to the reason of the error ? I did install marabou few months ago and the cmake was working perfectly.

Thank you

Best regards

**Comment by alexopenu** [comment]
Hi

I have also been having issues with the openBLAS library recently -- not sure how to solve them at the moment, so for now I am working  without it. If the issue persists, I suggest trying switching the ENABLE_OPENBLAS flag OFF [here](https://github.com/NeuralNetworkVerification/Marabou/blob/master/CMakeLists.txt#L16) and seeing what happens. 

Good luck

**Comment by guillaumevidot** [comment]
Hi, 

I had the same problem. 
By setting ENABLE_OPENBLAS flag OFF, I solved the error mention by @mducoffe.

But unfortunately I got the following when running "cmake --build ." (cf [installation documentation](https://neuralnetworkverification.github.io/Marabou/Setup/0_Installation.html)):

[  0%] Building CXX object CMakeFiles/MarabouHelper.dir/deps/CVC4/context/context.cpp.o
clang: error: argument unused during compilation: '-MMD' [-Werror,-Wunused-command-line-argument]
make[2]: *** [CMakeFiles/MarabouHelper.dir/deps/CVC4/context/context.cpp.o] Error 1
make[1]: *** [CMakeFiles/MarabouHelper.dir/all] Error 2
make: *** [all] Error 2

Do you have a clue how solve this error ? 

Thank you 

Regards

**Comment by anwu1219** [comment]
Hi, 

It seems the issue is quite prevalent when one upgraded to Catalina. And the second solution seems to be a clean one:
https://stackoverflow.com/questions/51761599/cannot-find-stdio-h

I created a PR (https://github.com/NeuralNetworkVerification/Marabou/pull/509) for this.
