### ISSUE TITLE
Questionable dimension of the ACAS XU network

### ISSUE THREAD

**Issue by persistz** [NeuralNetworkVerification/Marabou#471]
Using `ACASXU_experimental_v2a_1_1.nnet` as a demo,
according to `Marabou/maraboupy/MarabouNetworkNNet.py`, the 9th line of the net file represents the means for normalizations and the next line represents ranges for normalizations.

The values are: 
1.9791091e+04,0.0,0.0,650.0,600.0,7.5188840201005975,
60261.0,6.28318530718,6.28318530718,1100.0,1200.0,373.94992,

So why does an input with size=5 needs 6 means and ranges?

**Comment by AleksandarZeljic** [comment]
The sixth value is for normalization of all the outputs. For more details see .nnet format at https://github.com/sisl/NNet/blob/master/README.md

**Comment by persistz** [comment]
> The sixth value is for normalization of all the outputs. For more details see .nnet format at https://github.com/sisl/NNet/blob/master/README.md

Thanks a lot, closed.
