### ISSUE TITLE
onnx format

### ISSUE THREAD

**Issue by khedher1984** [NeuralNetworkVerification/Marabou#477]
Hello,
I have a segmentation fault when test a onnx format.
I use the Following command:

Marabou resources/onnx/mnist_relu_3_50.onnx resources/properties/mnist/image1_target2_epsilon0.005.txt

Can you help me ?
Best regards.

**Comment by anwu1219** [comment]
Hi,

Thanks for your interest in the tool. Unfortunately to analyze the onnx format, you have to use the python API. 
Here is an example: https://github.com/NeuralNetworkVerification/Marabou/blob/master/maraboupy/examples/2_ONNXExample.py

To add inequality constraints you could use  https://github.com/NeuralNetworkVerification/Marabou/blob/b0e29fb43b6722dfe9b5a90cc1353990aa732327/maraboupy/MarabouNetwork.py#L172

Please let me know if you have trouble running the tool.

**Comment by khedher1984** [comment]
I thank you for your feedback. I will test the python API and get back to you.
As an alternative and before contacting you, I use dnnv https://dnnv.readthedocs.io/en/stable/# where marabou is integrated. The advantage of dnnv is the possibility of accepting onnx format. Even with DNNV, I cannot launch marabou and I have a fault segmentation error. 

If you allow me, I have another question, in this paper https://arxiv.org/pdf/2105.12841v1.pdf, it is mentioned that marabou accepts 12 onnx operations (Table 12). Do you have any idea on that? Does marabou accept large size models like ImageNet or AlexNet (with of course only conv and piecewise activation functions)?

Thank you in advance.

**Comment by anwu1219** [comment]
Thanks for this information. I have not tried to use DNNV to launch Marabou. I do believe with the python API it should work.

Regarding supported onnx operations, the lines here described the operations that Marabou supports: https://github.com/NeuralNetworkVerification/Marabou/blob/b0e29fb43b6722dfe9b5a90cc1353990aa732327/maraboupy/MarabouNetworkONNX.py#L174-L197

I have tried to launch Marabou with off-the-shelf large models but there appears to be operations that we could have but not yet supported. If the model contains only supported operations, marabou should be able to at least parse it.
