### ISSUE TITLE
Properties

### ISSUE THREAD

**Issue by khedher1984** [NeuralNetworkVerification/Marabou#484]
Hello,
I am comparing marabou with other neural network verification tools on ACAS. However, I can only find the files associated with the first 4 properties.
Could you please tell me where I could find the implementation rest of the properties. 
Thanks in advance 
Sincerely.

**Comment by AleksandarZeljic** [comment]
Hi, it took me a bit to find them, but here is a collection of the ACAS properties. It is pretty old so disjunction properties are split up into separate queries
[acas_properties.tar.gz](https://github.com/NeuralNetworkVerification/Marabou/files/7628643/acas_properties.tar.gz).

Let me know if there are any other questions or if I can close the Issue.

**Comment by MatthewDaggitt** [comment]
> It is pretty old so disjunction properties are split up into separate queries acas_properties.tar.gz.

@AleksandarZeljic I'm intrigued by this comment. It sounds like you're implying that disjunctions no longer need to be split up into separate queries?

**Comment by AleksandarZeljic** [comment]
@MatthewDaggitt My comment had future seeping into it, with VNN-LIB there should be support for disjunctions. We have internal representation for them, but it has not been tested properly, nor exposed to the user yet.

**Comment by JonasHanselle** [comment]
Hello everyone,
following up on this issue, are there property files for the other networks in the resources that could be made available? So far, there are only the 4 acas property files and the mnist examples.
Best regards
Jonas

**Comment by idan0610** [comment]
This issue has most likely become stale and is being closed. If you still need the relevant property files, please contact us or open a new issue.
