### ISSUE TITLE
Supported input query formats

### ISSUE THREAD

**Issue by MatthewDaggitt** [NeuralNetworkVerification/Marabou#490]
Marabou is listed as a supporter of [VNNLib](http://www.vnnlib.org/software/). However, reading through the wiki page on [input formats](https://github.com/NeuralNetworkVerification/Marabou/wiki/Marabou-Input-Formats), there doesn't seem to be support for taking in properties in the VNNLib format.

What is the status of support for the VNNLib input format?

**Comment by AleksandarZeljic** [comment]
Hi @MatthewDaggitt, we currently have support for networks in the ONNX format via the maraboupy Python interface and properties can be encoded via the interface as well. The full native support for the VNN-LIB format is on our TODO list.

**Comment by MatthewDaggitt** [comment]
Thank you for your reply @AleksandarZeljic! So unfortunately we're looking to call Marabou from the command line as we're trying to call it automatically and we're not working in Python. We were hoping to run it using Onnx files, but it sounds like we'll have to convert them to the `.nnet` format first if we're calling it from the command line?

**Comment by AleksandarZeljic** [comment]
That is one way, another workaround would be to load the .onnx files via Python interface and specify the property and then save the query in Marabou's input query format. Marabou can then run the saved query from the command line. Does that help?

**Comment by MatthewDaggitt** [comment]
Unfortunately not. So our current setup is that we write the property in a high-level property specification language whose compiler is implemented in Haskell. It then compiles down the property to something readable by Marabou (was hoping VNNLib but can make do with the default input format used in e.g. [this file](https://github.com/NeuralNetworkVerification/Marabou/blob/master/resources/properties/acas_property_2.txt)). It then calls Marabou on the compiled property automatically. Unfortunately this means at no stage in this pipeline are we working with the property in Python.

**Comment by MatthewDaggitt** [comment]
Speaking of which, could I clarify what exactly is allowed in the Marabou property format described [here](https://github.com/NeuralNetworkVerification/Marabou/wiki/Marabou-Input-Formats). It says "Each line contains a single inequality and the lines are implicitly connected by a conjunction" which implicitly suggests that there are no restrictions on the inequalities. However as examples you only give inequalities between a single variable and a single constant. 

Obviously, given the underlying solving procedure, the inequalities must be linear in the variables, but are there other restrictions? For example which of the following are valid inequalities to take as input?
- `x0 + 1 <= 1`
- `x0 <= x1`
- `x0 + x1 <= 1`

**Comment by MatthewDaggitt** [comment]
Okay so having found and read through [this file](https://github.com/NeuralNetworkVerification/Marabou/blob/master/src/input_parsers/PropertyParser.cpp) I've come up with the following grammar for the property files:
```
Scalar         ::= <double>
InputVariable  ::= x<integer>
OutputVariable ::= y<integer>
Variable       ::= InputVariable | OutputVariable
Rel            ::= >= | = | <=
Coefficient    ::= + | - | <double>
Addend         ::= Coefficient Variable                              (no separating space)
Line           ::= [Addend] Rel Scalar
Property       ::= [Line]
```

Is there anything I've missed? 

I would open a PR to update the [Wiki](https://github.com/NeuralNetworkVerification/Marabou/wiki/Marabou-Input-Formats) page with it, but it appears one can't update the Wiki via a PR on Github. If it is accurate, would you consider adding the grammar to the page?

**Comment by AleksandarZeljic** [comment]
Thanks, @MatthewDaggitt, I've updated the Wiki page ton include the grammar. I added the hidden variables to the grammar for the sake of completeness.
