### ISSUE TITLE
Advice on adding support for `.onnx` files to the command line interface

### ISSUE THREAD

**Issue by MatthewDaggitt** [NeuralNetworkVerification/Marabou#498]
I have multiple onnx networks I would like to verify, and I cannot use MarabouPy as I am not working in a Python environment. One approach would be to convert them to the [NNet format](https://github.com/sisl/NNet) but that repo seems to be very behind the times (e.g. uses Tensorflow 1) and no matter what I do I can't get it to work, and anyway it's in Python so again I can't include it as a a regular part of my workflow.

So I am about to embark on a possibly fool-hardy quest to add support for onnx files to the command line interface for Marabou. My plan is as follows:

- Add a new `OnnxParser.h/cpp` to `src/input_parsers`
- Add a new conditional at the point below to use either the `AcasParser` (I guess should really be called `NNetParser`) or the `OnnxParser` depending on the extension of the network file. https://github.com/NeuralNetworkVerification/Marabou/blob/ffd353b09ff1e36deca1ca51cd2d93fbf5c97c71/src/engine/Marabou.cpp#L91-L93

 I was wondering if anyone had any advice or whether there were any objections to adding `onnx` as a dependency to Marabou?

**Comment by MatthewDaggitt** [comment]
Okay so documenting my journey:

- At the moment only the [onnxruntime](https://github.com/microsoft/onnxruntime) library that is used to run the onnx models has documented public C/C++ bindings, the [onnx](https://github.com/onnx/onnx) library that defines their internal format does not.
- Unfortunately `onnxruntime` does not let you inspect the model internals as far as I can see. Adding C/C++ bindings for `onnx` is on the long term roadmap but no-one is working on it now.
- This (closed) [issue](https://github.com/onnx/onnx/issues/418) suggest that it *is* possible to use the C/C++ [internal utilities](https://github.com/onnx/onnx/tree/master/onnx) to read in the `.onnx` files either via the `onnx` internal utilities or using protobuf (as `.onnx` files are really just protobufs)

**Comment by AleksandarZeljic** [comment]
Hi @MatthewDaggitt, we would absolutely welcome addition of `.onnx` format to Marabou natively. Your outline above makes sense and I don't think we can avoid adding dependency to `.onnx`.

I found a small example which may be useful - reading `.onnx` files as a protobuf in C++ [on stackoverflow](https://stackoverflow.com/questions/67301475/parse-an-onnx-model-using-c-extract-layers-input-and-output-shape-from-an-on).

Let me know if you have any questions or if you need help.

**Comment by MatthewDaggitt** [comment]
Thanks for the example, super useful!

Okay, so as one might expect I'm having far more trouble with the cmake build system than writing the actual code (again first time writing any C++ so bear with me). What I've got so far is [here](https://github.com/MatthewDaggitt/Marabou/commit/4b40871ff2e8adbed2f740c292a81b54526bd179#).

- I've added a script to download the `.proto` file from the `onnx` Github repo and compile it using `protoc` which generates the correct `.c` and `.h` files.
- In the top-level CMakelist file I've added commands run the script (will add guards later), and add that directory to the list of `includes` using `include_directories(${ONNX_DIR})`.

So far so good. The build system picks up the file, analyses it and then tries to build `protobuf` files which I have installed on my system. This is where it all goes wrong though as I get a crazy numbers of syntax errors in the protobuf header files. Here is a small sample of them:
```
/usr/include/google/protobuf/arena.h:71:7: error: expected identifier before ‘(’ token
   71 | class Message;        // defined in message.h
      |       ^~~~~~~
/usr/include/google/protobuf/arena.h:71:7: error: expected unqualified-id before ‘!’ token
   71 | class Message;        // defined in message.h
      |       ^~~~~~~
/usr/include/google/protobuf/arena.h:71:7: error: expected ‘)’ before ‘!’ token
In file included from /home/matthew/Code/AISEC/Marabou/tools/onnx-1.10.2/onnx.proto3.pb.h:23,
                 from /home/matthew/Code/AISEC/Marabou/src/input_parsers/OnnxParser.h:19,
                 from /home/matthew/Code/AISEC/Marabou/src/engine/Marabou.h:20,
                 from /home/matthew/Code/AISEC/Marabou/src/engine/main.cpp:18:
/usr/include/google/protobuf/arena.h: In member function ‘void google::protobuf::Arena::Own(T*)’:
/usr/include/google/protobuf/arena.h:384:57: error: template argument 2 is invalid
  384 |     OwnInternal(object, std::is_convertible<T*, Message*>());
      |
```
From some digging on Google, [this thread](https://stackoverflow.com/questions/18620621/compile-error-due-to-syntax-error-in-header-file) stands out the most, which describes how macros defined in one library can interfere with code in another and cause such syntax errors. However, even when I move the onnx include statement nearly to the top of the file I'm still getting similar errors.

So my question is, are any of the Marabou dependencies or Marabou itself known to have dodgy macros in them? Or do I need to go looking for a different culprit?

**Comment by AleksandarZeljic** [comment]
Hmm, I have not encountered such an issue before. It is certainly possible that a macro somewhere misbehaves. Before we start looking for them, can you confirm that the small example from SO compiles using the `.onnx` headers without these issues?

**Comment by AleksandarZeljic** [comment]
Ok, I found the culprit - it is in our dependencies from CVC4. If you comment out lines 407 and 422 in deps/CVC4/base/output.h the errors go away.

**Comment by MatthewDaggitt** [comment]
Thanks! That was impressively quick tracking the issue down. Do you mind me asking briefly how you managed to find the culprit? 

Okay, I'm back on track!

**Comment by MatthewDaggitt** [comment]
I also needed to disable the `InternalError` macro in `deps/CVC4/base/check.h` as well, but I've now succeeded in linking against the protobuf library and I'm now actively reading the `.onnx` file :tada:

**Comment by AleksandarZeljic** [comment]
If your hunch regarding a macro being the problem was correct it made sense that it would be called `Message` or something along those lines in order to result in the error that was reported. So that is what I searched for. 

I didn't find it immediately, because I only searched in the `src` directory, but after inspecting the error messages further, I found a place where a google include was complaining about CVC4's data structures which made me realize that I didn't search dependencies (`dep` folder). 

Hm, interesting re `InternalError`. What OS/compiler are you using? I didn't need to touch that to get it to compile.

I may need to look into stripping down those CVC4 dependencies to bare bones. We didn't touch them to make it easy to include a newer version of the files in the future.

**Comment by MatthewDaggitt** [comment]
Thanks for the explanation!

So the `InternalError` problem only occurred during linking rather than compilation. Commenting it out didn't seem to affect anything though so :man_shrugging:

**Comment by AleksandarZeljic** [comment]
Oh, I see, that makes sense. Yeah, if nothing is complaining then it is not used.

**Comment by MatthewDaggitt** [comment]
Just to say, I'm at a conference this week so will probably go silent, but will hopefully finish this off the week after I get back.

**Comment by MatthewDaggitt** [comment]
@AleksandarZeljic , I'm making progress but finding myself needing to represent arbitrary tensors and manipulate their shapes, e.g. https://github.com/NeuralNetworkVerification/Marabou/blob/acd916a41959538d009fd26567fb53b881acbfc0/maraboupy/MarabouNetworkONNX.py#L769

Is there any library currently included in Marabou to do that? If not do you have any preferences for an external library?

**Comment by MatthewDaggitt** [comment]
Hmm looks like the existing OpenBLAS library is probably the best bet...

**Comment by AleksandarZeljic** [comment]
Hi @MatthewDaggitt, we already use OpenBLAS so that would be the preferable option. Sorry for the slow replies, I lost track of the thread.
