### ISSUE TITLE
Implementation of other activation functions

### ISSUE THREAD

**Issue by chrcoc** [NeuralNetworkVerification/Marabou#510]
Hi, 
could you provide a few pointers where to start when implementing new activation functions (i.e. piece-wise linear and also non-linear)? 

Thank you

**Comment by anwu1219** [comment]
Hi,

Thanks for your interest in the code base.

The place to start is the two base classes: src/engine/PiecewiseLinearConstraint.h and src/engine/TranscendentalConstraint.h, which are inherited by classes like ReluConstriant, MaxConstraint, SigmoidConstraint etc. Generally you want to implement all the virtual functions in those base classes for your new activation functions.
I would suggest looking at existing constraint class similar to what you want to implement (e.g., LeakyReLU is probably going to be similar to ReLU). Note that the TranscendentalConstraint is currently under development so I'd suggest coordinate with us early on if you are interested in adding to that. 

After this step, there are several more considerations for improving runtime performance which we can discuss later:
1. You probably also want to extend the src/nlr folder which handles bound tightening passes like in CROWN/ERAN.
2. Extend [the MILP Encoder ](https://github.com/NeuralNetworkVerification/Marabou/blob/0952bcc11fe841cdb17874519bb99ab7484fd528/src/engine/MILPEncoder.cpp#L46)
3. Extend some other bound tightening passes.
