### ISSUE TITLE
cannot import name 'MarabouCore' from 'maraboupy'

### ISSUE THREAD

**Issue by cxyang1997** [NeuralNetworkVerification/Marabou#538]
Hi,

I follow the Readme to make the file and then run the queries for aurora. But I encountered an error as follows:

```
Traceback (most recent call last):
  File "queries/marabou_property_1.py", line 2, in <module>
    from maraboupy import Marabou, MarabouUtils, MarabouCore
  File "/home/xxx/Marabou/maraboupy/Marabou.py", line 20, in <module>
    from .MarabouNetworkNNet import *
  File "/home/xxx/Marabou/maraboupy/MarabouNetworkNNet.py", line 17, in <module>
    from maraboupy.MarabouUtils import *
  File "/home/xxx/Marabou/maraboupy/MarabouUtils.py", line 16, in <module>
    from maraboupy import MarabouCore
ImportError: cannot import name 'MarabouCore' from 'maraboupy' (/home/xxx/Marabou/maraboupy/__init__.py)
```

I checked that I can use python to `import maraboupy`. So I do not know where I should start to debug. Could you help with this?

Thank you very much!

**Comment by lucaslulu** [comment]
Same issue happens when I tried to pip install maraboupy-NeuralNetworkVerification==0.0.0

**Comment by anwu1219** [comment]
Hi there, could you please check whether the maraboupy binary is installed for the same python version that you're running your script with?  For instance, if the binary's name is ./maraboupy/MarabouCore.cpython-38-x86_64-linux-gnu.so, then it's installed for python 3.8. 
Please also make sure that you added the ./Marabou directory to the python path before importing.
`import sys`
`sys.path.append("path/to/Marabou")

**Comment by cxyang1997** [comment]
hi, 

I solved this by adding -DBUILD_PYTHON=ON during building.

Thanks for the reply.
