### ISSUE TITLE
[PLEASE HELP] Is there any way in Marabou to write a DNF constraints with Marabou python API?

### ISSUE THREAD

**Issue by HatsuneMK00** [NeuralNetworkVerification/Marabou#547]
I'm trying using Marabou to solve some satisfiability problems and I'm new to the SMT-based method. I'm curious on whether there exists a way to write a CNF constraints in Marabou with its python API? I want to write constraints like <math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mo stretchy="false">(</mo><msub><mi>X</mi><mn>1</mn></msub><mo>∧</mo><msub><mi>Y</mi><mn>1</mn></msub><mo stretchy="false">)</mo><mo>∨</mo><mo stretchy="false">(</mo><msub><mi>X</mi><mn>2</mn></msub><mo>∧</mo><msub><mi>Y</mi><mn>2</mn></msub><mo stretchy="false">)</mo><mo>∨</mo><mo>.</mo><mo>.</mo><mo>.</mo><mo>∨</mo><mo stretchy="false">(</mo><msub><mi>X</mi><mi>n</mi></msub><mo>∧</mo><msub><mi>Y</mi><mi>n</mi></msub><mo stretchy="false">)</mo></math>. Or I must convert it into CNF and use disjunction constraint? Thanks a lot.

**Comment by HatsuneMK00** [comment]
I think this answers my question! Thanks a lot!

**Comment by HatsuneMK00** [comment]
Hi, @anwu1219 I'm sorry to reopen this issue, but I wonder if there is a way to write a 'less or larger than' relation in the equation of disjunction constraints? As far as I know, the equation supports equation type of LE, GE and EQ. While I want to write something like 'constraints = [[x < 1 and y < 1], [eq2]]', is it possible? Thanks a lot!

**Comment by anwu1219** [comment]
Hi @HatsuneMK00 ,

Unfortunately currently we do *not* support strict inequalities. One way to work around it is to specify something like x + epsilon <= 1 and epsilon = 0.00001. 

Andrew

**Comment by HatsuneMK00** [comment]
Thanks for your reply! I'm trying this epsilon way and it works partially for me now.
And just for curious, is it possible to restrict a variable to have only integer value and would that improve the running time of Marabou?

**Comment by anwu1219** [comment]
Hi @HatsuneMK00 , right now there is no convenient way to restrict a variable to be only integer value, except adding a disjunction constraint. This adds non-linearity to the problem and might increase the run time.

**Comment by HatsuneMK00** [comment]
I expect to have effect of `var[0]=0 and var[1]=0 and ... and var[-1]=0` with disjunction constraints, and I'm using disjunction constraints like this: 
```python
for var in net.inputVars[0]:
    # eq1: 1 * var = 0
    eq1 = MarabouCore.Equation(MarabouCore.Equation.EQ);
    eq1.addAddend(1, var);
    eq1.setScalar(0);
    net.addDisjunctionConstraint([[eq1]])
    net.setLowerBound(var, 0)
    net.setUpperBound(var, 1)
```
By this code I want to use disjunction constraint to set all var to 0. But it gives a result of unsat when I run `net.solve()`
And I guess the following code using `network.addEqulity()` have similar effect as above so I also tried it: 
```python
for var in net.inputVars[0]:
    # eq1: 1 * var = 0
    net.addEqulity([var], [1], 0)
    net.setLowerBound(var, 0)
    net.setUpperBound(var, 1)
```
This gives me a sat result when I add inequality constraints on the output vars of network.

I can't figure out the reason why the code using disjunction constraints doesn't behave like the second code block(and also is not what I expect). Did I misunderstand the effect of disjunction constraints? Or just there is something wrong with the code? 
Thanks!

**Comment by HatsuneMK00** [comment]
This issue is solve with solution given in #551 .
