### ISSUE TITLE
bug in the precision of SaveQuery

### ISSUE THREAD

**Issue by guyam2** [NeuralNetworkVerification/Marabou#555]
Hi 

I found a precision issue within the **saveQuery()** method in maraboupy: when saving an input query it (currently) truncates all digits after the sixth decimal digit - which can alter the satisfiability, due to the fact that the original variables have a much higher precision. 

For example - in the attached zip with 2 ipqs:
1. **_ipq_saved_precision_** - a saved input query (this is **UNSAT**)
2. **_ipq_saved_precision_with manual_fix_** - the same input query with additional precision (this is **SAT**)

[ipqs.zip](https://github.com/NeuralNetworkVerification/Marabou/files/8404043/ipqs.zip)

I suggest maybe we save the digits with a higher precision? It will make the ipq text file larger but can make the result more reliable.

What do you suggest?

Thanks!

**Comment by idan0610** [comment]
This issue has most likely become stale and is being closed. If you think this issue is still relevant, please open a new issue.
