### ISSUE TITLE
Can I reset all constraints on MarabouNetwork without load it again

### ISSUE THREAD

**Issue by HatsuneMK00** [NeuralNetworkVerification/Marabou#558]
Hi! I'm curious about whether I can remove all constraints added on a MarabouNetwork while keeping the network itself? Currently I've tried the `MarabouNetwork.clear()` but it seems to clear the whole network together with constraints. So I'm loading the network every time I want to solve a verification problem. Is there any solution that I could remove constraints only and reuse the network itself, avoiding loading it from file again?

**Comment by anwu1219** [comment]
Hi @HatsuneMK00 , perhaps you could create a network object from the network file. Then every time you need to check some properties, make a deep copy (with the built-in copy.deepcopy method) of the network and add constraints on the copy?
