### ISSUE TITLE
Is multiplication of two variables, to put a constraint on their product possible in Marabou?

### ISSUE THREAD

**Issue by KhanTooba** [NeuralNetworkVerification/Marabou#564]
I want to verify properties of DNN in Marabou but I want to put constraints on the edge weights and biases also. For this purpose, I have encoded the DNN as a marabou query using MarabouCore library and I need to perform matrix multiplication for obvious reasons. However, I am unable to find a method by which I can put constraints on the product of two Marabou variables.

**Comment by guykatzz** [comment]
Hi KhanTooba,
Variable multiplication is unfortunately not supported by Marabou. The tool is based on linear programming, which only allows multiplying variables by scalars. One possible work-around: if you have z=x*y, and you know that 1<=y<=2, you can write that x<=z<=2z to get a sound over-approximation of the value of z.
