### ISSUE TITLE
IndexError: map::at

### ISSUE THREAD

**Issue by KhanTooba** [NeuralNetworkVerification/Marabou#565]
What does this error mean in Marabou? Someone please help.

**Comment by guykatzz** [comment]
This indicates that you are trying to access a map (dictionary) key that doesn't exist.

**Comment by Sids2k** [comment]
I am also getting this error. 
When I split the equation from EQ to GE and LE, it seems to work without throwing this error.
Eg. 
`equation_query4 = MarabouCore.Equation(MarabouCore.Equation.EquationType.EQ)

equation_query4.addAddend(1, 18)

equation_query4.setScalar(-0.0)

inputQuery.addEquation(equation_query4)` 

This does not work, but the following works:

`equation_query2 = MarabouCore.Equation(MarabouCore.Equation.EquationType.GE)

equation_query2.addAddend(1, 18)

equation_query2.setScalar(-0.0)

inputQuery.addEquation(equation_query2)

equation_query3 = MarabouCore.Equation(MarabouCore.Equation.EquationType.LE)

equation_query3.addAddend(1, 18)

equation_query3.setScalar(-0.0)

inputQuery.addEquation(equation_query3)`

No other part of the code was touched, but one throws an IndexError and the other gives me a SAT result.
