### ISSUE TITLE
Runtime Error when using Gurobi and Bound tightening

### ISSUE THREAD

**Issue by marcel-v** [NeuralNetworkVerification/Marabou#571]
Hi,

I observe an runtime error when running Marabou with this [query](https://github.com/NeuralNetworkVerification/Marabou/files/8900700/query.txt) when using _--lp-solver gurobi_ and any bound tightening strategy, i.e., **not** using _--tightening-strategy none_.

I can trace the error to a bad access in `Tableau::updateVariableToComplyWithUpperBoundUpdate( unsigned int, double )`, 
specifically, `_variableToIndex[variable]` (Tableau.cpp:1770),
see the [stack](https://github.com/NeuralNetworkVerification/Marabou/files/8900770/stack.txt).
At access time, `_variableToIndex` still points to `NULL`.

Commit is **492c1b8c703c8a383f421468a104c34710e6d26d**.

Thanks in advance for any feedback!

Best,
Marcel

**Comment by anwu1219** [comment]
Hi @marcel-v , thanks for your interest in the tool and tracking down the error. This does seem to be a issue stemming from this latest commit. 
We will fix the bug asap. 
For now, could you please revert back to the previous commit 2641ce74ccf0ebb53345c4a0f6b4c773df40e8a4? This one should work.

**Comment by anwu1219** [comment]
Hi @marcel-v , please try the latest master. should be fixed.

**Comment by marcel-v** [comment]
> Hi @marcel-v , please try the latest master. should be fixed.

Great, works!

**Comment by marcel-v** [comment]
There appears to be another invalid access to the tableau internals when using Gurobi with [this query](https://github.com/NeuralNetworkVerification/Marabou/files/8924583/query.txt), resulting in
[this stack](https://github.com/NeuralNetworkVerification/Marabou/files/8924585/stack.txt).

I am at latest commit  eb93d44e66aec9e374691afc31cd2b3916d76a20.

**Comment by anwu1219** [comment]
Hi @marcel-v , I apologize for the inconvenience. A new Pr should fix these issues, and all the regression tests now pass with Gurobi on.
