### ISSUE TITLE
Non-Termination during Preprocessing

### ISSUE THREAD

**Issue by marcel-v** [NeuralNetworkVerification/Marabou#573]
Hi,

there appears to be the risk to enter an infinite loop in the [preprocessor](https://github.com/NeuralNetworkVerification/Marabou/blob/master/src/engine/Preprocessor.cpp).
I observed the behavior using this [query](https://github.com/NeuralNetworkVerification/Marabou/files/8927297/query.txt).
Annotating lines 520 & 521:

`tighterBoundFound = true;`
`setUpperBound( tightening._variable, tightening._value );`

with

`tighterBoundFound = true;`
`std::cout << "--- Tightening UB --- (var: " << tightening._variable << ")" << std::endl;`
`std::cout << "Current Bounds : [" << getLowerBound(tightening._variable) << ", " << getUpperBound(tightening._variable) << "]" << std::endl;`
`setUpperBound( tightening._variable, tightening._value );`
`std::cout << "Tightened UB: " << getUpperBound(tightening._variable) << std::endl;`

will (repeatedly) produce the following output:

_--- Tightening UB --- (var: 105)
Current Bounds : [8.1e-06, 8.1e-06]
Tightened UB: 0_

One issue seems to be that

`if ( FloatUtils::areEqual( getLowerBound( tightening._variable ), getUpperBound( tightening._variable ), GlobalConfiguration::PREPROCESSOR_ALMOST_FIXED_THRESHOLD ) )` 
`setUpperBound( tightening._variable, getLowerBound( tightening._variable ) );`

(line 524 et sqq.) will reset the upper bound to 8.1e-06.

Thanks in advance for any feedback!

**Comment by anwu1219** [comment]
Hi @marcel-v , could you try increasing this parameter?

https://github.com/NeuralNetworkVerification/Marabou/blob/eb93d44e66aec9e374691afc31cd2b3916d76a20/src/configuration/OptionParser.cpp#L145

**Comment by marcel-v** [comment]
Increasing the preprocessor bound tolerance appears to have no impact on the issue.
I tested this by multiplying the default with factors in {10, 10^2, ..., 10^9}, specifically here:
https://github.com/NeuralNetworkVerification/Marabou/blob/eb93d44e66aec9e374691afc31cd2b3916d76a20/src/configuration/Options.cpp#L73 

Actually, shouldn't it be possible to fix this issue independent of specific tolerance values by moving the "is-equal-under-almost-fix-tolerance" check 
https://github.com/NeuralNetworkVerification/Marabou/blob/eb93d44e66aec9e374691afc31cd2b3916d76a20/src/engine/Preprocessor.cpp#L524 
right to the tightening.
For instance after
https://github.com/NeuralNetworkVerification/Marabou/blob/eb93d44e66aec9e374691afc31cd2b3916d76a20/src/engine/Preprocessor.cpp#L514 
(i.e., the lower bound tightening)
one would add

`if (FloatUtils::areEqual( tightening._value , getUpperBound( tightening._variable ), GlobalConfiguration::PREPROCESSOR_ALMOST_FIXED_THRESHOLD)) {`

`setUpperBound(tightening._variable, tightening._value);`

`}`

Analogously for upper bound tightening and transcendental constraints.
At least for the specific query it works.
However, could this -- for arbitrary queries -- conflict with other parts of the preprocessing infrastructure?

**Comment by wu-haoze** [comment]
The suggested change is implemented in PR #675 .
