### ISSUE TITLE
Modify weights in MarabouNetwork

### ISSUE THREAD

**Issue by HatsuneMK00** [NeuralNetworkVerification/Marabou#576]
Hello! I'm wondering if I can get and modify the weight in MarabouNetwork.
Currently I'm using the `Marabou.read_onnx()` to read a onnx model from file. I want to modify some weights of that model after I load it from .onnx file.
Modify the weight of  onnx model , save it to file and load it again with Marabou should work, but I'm wondering if there is some other way to do that.
Thanks!

**Comment by anwu1219** [comment]
Hi @HatsuneMK00 , the alternative would be to modify the coefficients in the equations added by the add*Equations method in maraboupy/MarabouNetworkONNX.py.

This might be a bit error-proning but should be in principle doable.
