### ISSUE TITLE
Python API: cannot open the shared object file

### ISSUE THREAD

**Issue by kgoyal40** [NeuralNetworkVerification/Marabou#582]
Hi, I get the following error when trying to import maraboupy:

>>> from maraboupy import Marabou
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kshitij/Marabou/maraboupy/Marabou.py", line 17, in <module>
    from maraboupy.MarabouCore import *
ImportError: libboost_program_options.so.1.71.0: cannot open shared object file: No such file or directory
>>> from maraboupy import MarabouCore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libboost_program_options.so.1.71.0: cannot open shared object file: No such file or directory

Can you help me with this issue?

Thanks in advance!

**Comment by idan0610** [comment]
This issue has most likely become stale and is being closed. If the problem persists, please contact us or open a new issue.
