### ISSUE TITLE
Problem when running test with the Marabou Python Interface 

### ISSUE THREAD

**Issue by ameenam2** [NeuralNetworkVerification/Marabou#583]
Using the [Marabou Python Documentation](https://neuralnetworkverification.github.io/Marabou/Setup/0_Installation.html), I ran the command 
```
python -m pytest test/test_nnet.py. I get the following error message:
```
 I get the following error message:
==================================== ERRORS ====================================
______________________ ERROR collecting test/test_nnet.py ______________________
ImportError while importing test module '/Users/ameenamohammed/Marabou/maraboupy/test/test_nnet.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_nnet.py:9: in <module>
    from .. import Marabou
Marabou.py:17: in <module>
    from maraboupy.MarabouCore import *
E   ImportError: dlopen(/Users/ameenamohammed/Marabou/maraboupy/MarabouCore.cpython-39-darwin.so, 0x0002): tried: '/Users/ameenamohammed/Marabou/maraboupy/MarabouCore.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
=========================== short test summary info ============================
ERROR test/test_nnet.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.07s ===============================

 I added the marabou directory to the python path and even imported the marabou directory at the beginning of the file.

What can be done to resolve this issue? Thank you in advance

**Comment by idan0610** [comment]
This issue has most likely become stale and is being closed. If the problem persists, please contact us or open a new issue.
