### ISSUE TITLE
cmake error while build

### ISSUE THREAD

**Issue by CRhapsody** [NeuralNetworkVerification/Marabou#589]
when I follow the instruction of maraboupy and run
` cmake --build . -j 4`
then a error occured:

[ 11%] Building CXX object CMakeFiles/MarabouCore.dir/maraboupy/MarabouCore.cpp.o
In file included from /home/abc/MinimalDNNModificationLpar2020/Marabou/tools/pybind11-2.3.0/include/pybind11/pytypes.h:12,
                 from /home/abc/MinimalDNNModificationLpar2020/Marabou/tools/pybind11-2.3.0/include/pybind11/cast.h:13,
                 from /home/abc/MinimalDNNModificationLpar2020/Marabou/tools/pybind11-2.3.0/include/pybind11/attr.h:13,
                 from /home/abc/MinimalDNNModificationLpar2020/Marabou/tools/pybind11-2.3.0/include/pybind11/pybind11.h:49,
                 from /home/abc/MinimalDNNModificationLpar2020/Marabou/maraboupy/MarabouCore.cpp:17:
/home/abc/MinimalDNNModificationLpar2020/Marabou/tools/pybind11-2.3.0/include/pybind11/detail/common.h:112:10: fatal error: Python.h: Not found file or dictory
  112 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.

**Comment by idan0610** [comment]
This issue has most likely become stale and is being closed. If the problem persists, please contact us or open a new issue.
