### ISSUE TITLE
Installation issues on M1 mac and Windows

### ISSUE THREAD

**Issue by johnsonchau7** [NeuralNetworkVerification/Marabou#596]
Hi,

For M1 macs, is the build process with cmake require any special configuration? We faced this library not found error when running "cmake --build ." on m1 mac.

For windows, does the visual studio version matter for building? The guide mentioned VS 2017, however, we have 2019, which could be the cause of it (The second image is the error that occurred when running cmake --build . --config Release on windows and VS 2019)

![308510359_1122054891738775_7000231866903148150_n (2)](https://user-images.githubusercontent.com/55139040/195470140-cb77cca7-20f8-488d-bba6-8e4bccfdf835.png)
<img width="681" alt="Screen Shot 2022-10-01 at 6 58 54 pm (1)" src="https://user-images.githubusercontent.com/55139040/195470142-647320d6-463d-408a-87fe-12e8bb3d53de.png">

Note, I believe this is linked to this issue which has a PR ready: https://github.com/NeuralNetworkVerification/Marabou/issues/593

**Comment by Peipi98** [comment]
> I have the exact same problem while installing on M1 mac. Thus, #593 didn't fix it in my case.

Hi Marco!

I'm currently using Marabou with M1 and it builds correctly now. The authors also released relative python package , just do `pip install maraboupy`
