### ISSUE TITLE
MaxConstraint is not getting added

### ISSUE THREAD

**Issue by anaghaathavale** [NeuralNetworkVerification/Marabou#597]
I am unable to add maxConstraint to the input query. If I add it after any other piecewise linear constraint (Relu/Sign), it just duplicates the previous Relu/Sign constraint. If max is the only piecewise linear constraint that I add, then no constraint is displayed when I try to print the list of constraints. I tried adding it to an existing maraboupy example and also via Marabou.cpp to the input query. Doesn't work.
Regards.

**Comment by idan0610** [comment]
This issue has most likely become stale and is being closed. If the problem persists, please contact us or open a new issue.
