### ISSUE TITLE
Incorrect Marabou results on several BNN queries when DEEPSOI_SEARCH is off

### ISSUE THREAD

**Issue by OmriIsacHUJI** [NeuralNetworkVerification/Marabou#605]
I've noticed that in the current version, when turning the USE_DEEPSOI_LOCAL_SEARCH configuration off, Marabou returns an UNSAT result for several satisfiable BNN queries.

Specifically, the bug appeared in the queries:
    - mnist-bnn_index0_eps0.001_target7_sat.ipq
    - mnist-bnn_index1_eps0.001_target2_sat.ipq
    - mnist-bnn_index2_eps0.0001_target1_sat.ipq
    - mnist-bnn_index2_eps0.001_target1_sat.ipq

The bug did not appear in any other regression test, so it's possible that the bug is specific to BNN queries and/or sign constraints.

**Comment by anwu1219** [comment]
Hi Omri, this is interesting. Is there a particular reason that you are turning that flag off? The long term plan is to only support deepsoi.

**Comment by OmriIsacHUJI** [comment]
Hi Andrew,
I've turned the flag off for the proof production code, which will probably need modifications to support the deepsoi search.
I've noticed that the code failed on some BNN regression tests, but it doesn't seem to be related to proof production itself (the bug is reproduced on the main branch of Marabou with the only difference of the turning the flag off).

**Comment by idan0610** [comment]
It seems that this bug no longer exists in the latest version, so this issue is closed.
