### ISSUE TITLE
Unknown error when trying to use the result of max in an equation, followed by another max

### ISSUE THREAD

**Issue by anaghaathavale** [NeuralNetworkVerification/Marabou#615]
I am getting an unknown error when I try to use the result of MaxConstraint in more than one equation, followed by another MaxConstraint. I do not see any reason why this should not work. 
It works if there is only one equation but gives an unknown error if there are more than 1 equations. Please find attached the failedMarabouQuery.ipq file.
Thanks!

The below is essentially what causes the error. It works if I only have Equation eq2.

        Set<unsigned int> set1, set2;
        unsigned q2 = _inputQuery.getNumberOfVariables();
        _inputQuery.setNumberOfVariables(q2+1);
        _inputQuery.setLowerBound(q2, -5.0);
        _inputQuery.setUpperBound(q2, 5.0);
        unsigned q3 = _inputQuery.getNumberOfVariables();
        _inputQuery.setNumberOfVariables(q3+1);
        _inputQuery.setLowerBound(q3, -5.0);
        _inputQuery.setUpperBound(q3, 5.0);
        
        unsigned var2 = _inputQuery.getNumberOfVariables();
        _inputQuery.setNumberOfVariables(var2+1);

        Equation eq2;
        eq2.addAddend(1, q2);
        eq2.addAddend(-0.33, var2);            
        eq2.setScalar(0.33);
        _inputQuery.addEquation(eq2);
        set1.insert(q2);
        Equation eq3;
        eq3.addAddend(1, q3);
        eq3.addAddend(-0.67, var2);            
        eq3.setScalar(0.5);
        _inputQuery.addEquation(eq3);
        set1.insert(q3);
        
        unsigned fmax1 = _inputQuery.getNumberOfVariables();
        _inputQuery.setNumberOfVariables(fmax1+1);
        _inputQuery.setLowerBound(fmax1, -5.0);
        _inputQuery.setUpperBound(fmax1, 5.0);
        unsigned fmax2 = _inputQuery.getNumberOfVariables();
        _inputQuery.setNumberOfVariables(fmax2+1);
        _inputQuery.setLowerBound(fmax2, -5.0);
        _inputQuery.setUpperBound(fmax2, 5.0);
        unsigned neg_fmax1 = _inputQuery.getNumberOfVariables();
        _inputQuery.setNumberOfVariables(neg_fmax1+1);
        _inputQuery.setLowerBound(neg_fmax1, -5.0);
        _inputQuery.setUpperBound(neg_fmax1, 5.0);

        MaxConstraint *m = new MaxConstraint(fmax1, set1);
        _inputQuery.addPiecewiseLinearConstraint(m);
        
        Equation eq5;
        eq5.addAddend(1, fmax1);
        eq5.addAddend(1, neg_fmax1);            
        eq5.setScalar(0);
        _inputQuery.addEquation(eq5);
        set2.insert(neg_fmax1);

        unsigned neg_five_by_six = _inputQuery.getNumberOfVariables();
        _inputQuery.setNumberOfVariables(neg_five_by_six+1);
        _inputQuery.setLowerBound(neg_five_by_six, -0.83);
        _inputQuery.setUpperBound(neg_five_by_six, -0.83);
        set2.insert(neg_five_by_six);

        MaxConstraint *m1 = new MaxConstraint(fmax2, set2);
        _inputQuery.addPiecewiseLinearConstraint(m1);

[failedMarabouQuery.ipq.txt](https://github.com/NeuralNetworkVerification/Marabou/files/10324412/failedMarabouQuery.ipq.txt)

**Comment by idan0610** [comment]
This issue has most likely become stale and is being closed. If the problem persists, please contact us or open a new issue.
