### ISSUE TITLE
Ill-formed Tableau Assignment After Precision Restoration.

### ISSUE THREAD

**Issue by marcel-v** [NeuralNetworkVerification/Marabou#620]
Hi,

checking this [query](https://github.com/NeuralNetworkVerification/Marabou/files/10840139/query.txt), I observe a problem when restoring precision after high degradation has been found.

I use this [commit](https://github.com/NeuralNetworkVerification/Marabou/tree/14dd0f1446e3c980d408839150d342327ab73527) (built **without** Gurobi) with [GlobalConfiguration::USE_DEEPSOI_LOCAL_SEARCH = false](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/configuration/GlobalConfiguration.cpp#L27).

In release mode, Marabou returns **SAT** with an invalid input assignment, i.a, **x4 = nan**.

In debug mode this [verifyInvariants check ](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/PrecisionRestorer.cpp#L140) fails producing this output:
_Assignment for basic variable 4 (index 0) is not well formed: nan. Range: [-179 ... 368.0 ... 0, 179 ... 368.0 ...0]_

I believe (though you can consider this a guess) the issue can be traced back to this [Engine::postContextPopHook()](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/PrecisionRestorer.cpp#L52) call in PrecisionRestorer which then calls [BoundManager::restoreLocalBounds()](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/Engine.cpp#L2318) assigning [_storedLowerBounds and _storedUpperBounds to _lowerBounds and _upperBounds](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/BoundManager.cpp#L223). 
However [BoundManager::storeLocalBounds()](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/BoundManager.cpp#L214) (setting the _storedLowerBounds and _storedUpperBounds properly) is only called as part of [Engine::preContextPushHook()](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/Engine.cpp#L2305) which apparently is only called once a piecewise-linear constraint is split, i.e., [here](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/SmtCore.cpp#L172) which presumably has not happened for the given query when performing the restoration step.

At least, introducing a **_storedLowerBoundsFlag** in BoundManager to suppress any bound assignment in [BoundManager::restoreLocalBounds()](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/BoundManager.cpp#L223) if [BoundManager::storeLocalBounds()](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/BoundManager.cpp#L214) has not been called before, seems to fix the issue: High degradation occurs but a valid solution is returned.

I noticed that the long term plan is to [only support deepsoi](https://github.com/NeuralNetworkVerification/Marabou/issues/605). Though, while for the given query the issue is observed only for non-deepsoi, I wonder whether the issue might in general also occur when using deepsoi.

Thanks in advance for any feedback!

**Comment by idan0610** [comment]
It seems that this bug no longer exists in the latest version, so this issue is closed.
