### ISSUE TITLE
Violated Assertion in ReluConstraint::getPossibleFixes()

### ISSUE THREAD

**Issue by marcel-v** [NeuralNetworkVerification/Marabou#621]
Hi, 

checking this [query](https://github.com/NeuralNetworkVerification/Marabou/files/10887737/failed.txt) in debug mode results in violation of this [non-negative-fValue assertion](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/ReluConstraint.cpp#L298) in [ReluConstraint::getPossibleFixes()](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/ReluConstraint.cpp#L286).

I use this [commit](https://github.com/NeuralNetworkVerification/Marabou/tree/14dd0f1446e3c980d408839150d342327ab73527) (built **without** Gurobi) with [GlobalConfiguration::USE_DEEPSOI_LOCAL_SEARCH = false](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/configuration/GlobalConfiguration.cpp#L27).

The issue might be related to the difference in [relaxed basic-status precision in Tableau](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/Tableau.cpp#L424) vs [default epsilon precision](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/configuration/GlobalConfiguration.cpp#L35). The latter is used by the violated assertion above. The former is relevant for the preceding [allVarsWithinBounds()](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/Engine.cpp#L277) check.

Decreasing [GlobalConfiguration::DEFAULT_EPSILON_FOR_COMPARISONS](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/configuration/GlobalConfiguration.cpp#L35)  to **0.00000001** resolves the issue.

Though, I wonder whether implementing a branch for **FloatUtils::isNegative( fValue )** in [ReluConstraint::getPossibleFixes()](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/ReluConstraint.cpp#L286) might be a more robust fix to the issue.

Thanks in advance for any feedback!

Attached the **stack**:

ReluConstraint::getPossibleFixes() const ReluConstraint.cpp:298
Engine::fixViolatedPlConstraintIfPossible() Engine.cpp:770
Engine::performConstraintFixingStep() Engine.cpp:555
Engine::adjustAssignmentToSatisfyNonLinearConstraints() Engine.cpp:458
Engine::solve(unsigned int) Engine.cpp:282
[Inlined] Marabou::solveQuery() Marabou.cpp:200
Marabou::run() Marabou.cpp:60
main main.cpp:108

**Comment by idan0610** [comment]
It seems that this bug no longer exists in the latest version, so this issue is closed.
