### ISSUE TITLE
Why are the 4 properties of ACAS xu in marabou different from the 10 properties in ReLuplex? Are their properties universal to ACAS Xu?

### ISSUE THREAD

**Issue by fafawing** [NeuralNetworkVerification/Marabou#622]
Hello, I have a problem that has been bothering me. Why are the 4 properties of ACAS xu in marabou different from the 10 properties in ReLuplex? Are their properties universal to ACAS Xu? Are these four safety properties?

**Comment by guykatzz** [comment]
Hi Fafawing,
I believe the 4 properties in our repository are the same as the ones in the Reluplex properties. The properties here are for post-normalization values, which perhaps is the source of the confusion. All original 10 properties are safety properties.
