### ISSUE TITLE
InfeasibleQueryException results in invalid split stack

### ISSUE THREAD

**Issue by marcel-v** [NeuralNetworkVerification/Marabou#623]
Hi, 

checking this [query](https://github.com/NeuralNetworkVerification/Marabou/files/10911379/buggyStackDueToException.txt) in debug mode results in violation of this [_stack-_context-size assertion](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/SmtCore.cpp#L210) in [SmtCore::getStackDepth()](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/SmtCore.cpp#L208).

I use this [commit](https://github.com/NeuralNetworkVerification/Marabou/tree/14dd0f1446e3c980d408839150d342327ab73527) (building **without** Gurobi).
The issue can be observed for both [GlobalConfiguration::USE_DEEPSOI_LOCAL_SEARCH](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/configuration/GlobalConfiguration.cpp#L27) configurations.

The issue seems to be caused by [DisjunctionConstraint::updateFeasibleDisjuncts()](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/DisjunctionConstraint.cpp#L473) throwing an [InfeasibleQueryException](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/DisjunctionConstraint.cpp#L485) during the call to [_engine->applySplit( *split )](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/SmtCore.cpp#L178) in SmtCore.
This results in a partially constructed "context-stack-composition": [pushContext()](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/SmtCore.cpp#L173) is called prior to the exception, while [_stack.append( stackEntry )](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/SmtCore.cpp#L190) will not be called.
The exception will be caught in [Engine::solve()](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/Engine.cpp#L332), subsequently calling [SmtCore::popSplit()](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/SmtCore.cpp#L240) which will pop from **_context and _stack**, resulting in an invalid stack. 

Thanks in advance for any feedback!

**Comment by idan0610** [comment]
It seems that this bug no longer exists in the latest version, so this issue is closed.
