### ISSUE TITLE
Call to Engine::applyBoundTightenings() may have no effect.

### ISSUE THREAD

**Issue by marcel-v** [NeuralNetworkVerification/Marabou#624]
Hi,

investigating this [issue](https://github.com/NeuralNetworkVerification/Marabou/issues/623), I also found another one:
It seem that a call to [Engine::applyBoundTightenings()](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/Engine.cpp#L1900) will never have an effect. At least I can observe such behavior at [this point](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/Engine.cpp#L250) for the given [query](https://github.com/NeuralNetworkVerification/Marabou/files/10911379/buggyStackDueToException.txt).

The cause seems to be that, while the [recent tightenings in BoundManager](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/Engine.cpp#L1903) have not been feed to the Tableau yet, the bound of the tightening will only be set "inside" Tableau if the bound is [tighter than the bound already present in Tableau](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/Tableau.cpp#L1797). However, here Tableau actually [uses the bounds of BoundManager](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/Tableau.cpp#L40). Hence the [tightening call](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/Engine.cpp#L1908) to Tableau has no effect.
Now, the main issue is that only if the bound would be [set in Tableau](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/Tableau.cpp#L455) the [variable watchers](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/Tableau.h#L477) (like the piecewise-linear constraints) will be [notified](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/Tableau.cpp#L2129) to effectively prune infeasible piecewise-linear cases. 

Thanks in advance for any feedback!

**Comment by anwu1219** [comment]
Hi @marcel-v , is this problem resolved? The applyBoundTightenings() method is not meant to be invoked from outside of the class. As you correctly point out, the applyBoundTightenings() method does not itself do any tightening. It is used to pull changes after invocations of the actual tightening functions. If you let me know if you want to achieve I can provide more pointers.

**Comment by marcel-v** [comment]
Yes, applyBoundTightenings() does not do any tightening itself.
But apparently, at least as observed for the provided query, changes after previous tightening will also not be pulled due to [this check](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/Tableau.cpp#L1797), which essentially terminates "pulling the changes" if the updated bounds are not tighter than the bounds in BoundManager. However, at this point, BoundManager already contains the updated bounds.
As a consequence, piecewise-linear constraints will not be notified of tightened bounds. However, if they would be notified some of the piecewise-linear constraints might be [set to a fixed phase](https://github.com/NeuralNetworkVerification/Marabou/blob/14dd0f1446e3c980d408839150d342327ab73527/src/engine/ReluConstraint.cpp#L140).
I would like to achieve the latter.

**Comment by idan0610** [comment]
This issue has most likely become stale and is being closed. If the problem persists, please contact us or open a new issue.
