### ISSUE TITLE
TypeError with MarabouNetwork.addDisjunctionConstraint()

### ISSUE THREAD

**Issue by SuryaB1** [NeuralNetworkVerification/Marabou#652]
_**System Info:**_
_2019 Intel Core i9 MacBook Pro
macOS Ventura 13.4 (22F66)
Python 3.8.16_

Hi,

I am trying to add a disjunctive constraint to my network-based InputQuery roughly as follows (mainly, ```network.addDisjunctionConstraint(disjunction)``` towards the bottom of the script):
```python
# script.py
from maraboupy import Marabou
from maraboupy import MarabouCore
from maraboupy import MarabouUtils

# Read in the network from a TensorFlow savedModel format
network = Marabou.read_tf(filename = FILENAME, modelType="savedModel_v2")

eq1 = MarabouUtils.Equation(MarabouCore.Equation.EquationType.LE)
eq2 = MarabouUtils.Equation(MarabouCore.Equation.EquationType.GE)

inputVars = network.inputVars[0][0]
outputVars = network.outputVars[0].flatten()

# Build inequality constraints
for var in inputVars:
   coeff = 9
   eq1.addAddend(coeff, var)
   eq2.addAddend(coeff, var)

   network.setLowerBound(var, -1*SCALAR_BOUND)
   network.setUpperBound(var, SCALAR_BOUND)
eq1.addAddend(-1, outputVars[0])
eq2.addAddend(-1, outputVars[0])

# Add disjunction constraint from the two inequality constraints, eq1 and eq2
disjunction = [[eq1], [eq2]]
network.addDisjunctionConstraint(disjunction)

exitCode, vals, stats = network.solve("marabou.log")
``` 

After running the script involving the above code, I am met with the following error:
```python
Traceback (most recent call last):
  File "script.py", line 90, in <module>
    main()
  File "script.py", line 76, in main
    exitCode, vals, stats = network.solve("marabou.log")
  File "/Users/UserName/Documents/Marabou/maraboupy/MarabouNetwork.py", line 301, in solve
    ipq = self.getMarabouQuery()
  File "/Users/UserName/Documents/Marabou/maraboupy/MarabouNetwork.py", line 275, in getMarabouQuery
    MarabouCore.addDisjunctionConstraint(ipq, disjunction)
TypeError: addDisjunctionConstraint(): incompatible function arguments. The following argument types are supported:
    1. (inputQuery: InputQuery, disjuncts: List[List[Equation]]) -> None

Invoked with: <maraboupy.MarabouCore.InputQuery object at 0x176e28330>, [[<maraboupy.MarabouUtils.Equation object at 0x108e5dbb0>], [<maraboupy.MarabouUtils.Equation object at 0x176de6070>]]
``` 

Though the error message is suggesting incorrect input types, my disjunction input parameter is formatted as a List of Lists of Equations as mentioned in the MarabouNetwork.addDisjunctionConstraint() implementation (provided at the end of this post). 

My only hypothesis of the source of this error is using ```MarabouUtils.Equation``` for defining ```eq1``` and ```eq2```unlike using ```MarabouCore.Equation``` as done in the example "5_DisjunctionConstraintExample.py". The reason I am using ```MarabouUtils.Equation```, however, is due to originally receiving a TypeError for the MarabouCore.Equation constructor when passing in the valid input MarabouCore.Equation.EquationType.EQ.

Do these issues reflect potential bugs, or am I missing something that was not highlighted in the docs or examples?

_MarabouNetwork.addDisjunctionConstraint() implementation excerpt:_
```python
def addDisjunctionConstraint(self, disjuncts):
   """Function to add a new Disjunction constraint

   Args:
   disjuncts (list of list of Equations): Each inner list represents a disjunct
   """
   ...
```

**Comment by SuryaB1** [comment]
For further context, the other TypeError I mentioned in the original post that I was receiving from the ```MaraboutCore.Equation``` constructor was as follows:

```python
<class 'maraboupy.MarabouCore.Equation.EquationType'>
Traceback (most recent call last):
  File "script.py", line 67, in <module>
    main()
  File "script.py", line 56, in main
    vals, stats = network.solve("marabou.log")
  File "/Users/UserName/Documents/Marabou/maraboupy/MarabouNetwork.py", line 301, in solve
    ipq = self.getMarabouQuery()
  File "/Users/UserName/Documents/Marabou/maraboupy/MarabouNetwork.py", line 247, in getMarabouQuery
    eq = MarabouCore.Equation(e.EquationType)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. maraboupy.MarabouCore.Equation()
    2. maraboupy.MarabouCore.Equation(arg0: maraboupy.MarabouCore.Equation.EquationType)

Invoked with: <class 'maraboupy.MarabouCore.Equation.EquationType'>
```

And the original script that caused this other TypeError is roughly as follows:
```python
from maraboupy import Marabou
from maraboupy import MarabouCore

# Read in the network from a TensorFlow savedModel format
network = Marabou.read_tf(filename = FILENAME, modelType="savedModel_v2")

eq = MarabouCore.Equation(MarabouCore.Equation.EquationType.EQ)

inputVars = network.inputVars[0][0]
for var in inputVars:
   coeff = 9
   eq.addAddend(coeff, var)
eq.setScalar(50)

network.addEquation(eq, isProperty=True)
exitCode, vals, stats = network.solve("marabou.log")
```

**Comment by SuryaB1** [comment]
I was able to resolve the ```addDisjunctionConstraint()``` TypeError after switching
```python
eq1 = MarabouUtils.Equation(MarabouCore.Equation.EquationType.LE)
eq2 = MarabouUtils.Equation(MarabouCore.Equation.EquationType.GE)
```
to
```python
eq_le = MarabouCore.Equation(MarabouCore.Equation.EquationType.LE)
eq_ge = MarabouCore.Equation(MarabouCore.Equation.EquationType.GE)
```
by reverting to MarabouCore.Equation.

In fact, changing LE or GE to EQ (when inputting the equation into ```addDisjunctionConstraint``` later on) does not cause any errors, so it seems that ```MarabouCore.Equation``` works as input to ```addDisjunctionConstraint()``` but does not work with ```addEquation()```, while ```MarabouUtilities.Equation``` works as input to ```addEquation()```, but does not seem to work with ```addDisjunctionConstraint()```.

Why is this the case? Is this intended behavior?

**Comment by anwu1219** [comment]
Hi @SuryaB1 , thanks for resolving the issue on your own. What you found out is exactly correct. 

MarabouCore.Equation is the python binding of the C++ class Equation. MarabouUtils.Equation only lives in the Python API and is encoded into MarabouCore.Equation when the actual verification query is generated. This is a little confusing and the current behavior is not ideal. In the future, we should either drop MarabouUtils.Equation entirely or allow the user to encode either MarabouCore.Equation or MarabouUtils.Equation for the addDisjunctionConstraint() and addEquation() functions.
