### ISSUE TITLE
Installation via pip doesn't work for Windows

### ISSUE THREAD

**Issue by Peipi98** [NeuralNetworkVerification/Marabou#657]
Hello everyone!

Since there is the new maraboupy release I've tried to install it via pip command, but this error has occurred:

![telegram-cloud-photo-size-4-5906931005829267112-x](https://github.com/NeuralNetworkVerification/Marabou/assets/39802340/4fd26fab-01f3-446b-9101-c16838cc0b64)

Could it be a C/C++ compiler problem or else?

**Comment by MatthewDaggitt** [comment]
Marabou does not build on Windows. See https://github.com/NeuralNetworkVerification/Marabou#build-instructions-for-windows-using-visual-studio

**Comment by Peipi98** [comment]
Thanks!

Even thought there is no current support for windows, should we expect that further versions take it into account?
