### ISSUE TITLE
MarabouNetwork.solve() does not terminate with specific bound properties

### ISSUE THREAD

**Issue by SuryaB1** [NeuralNetworkVerification/Marabou#659]
Hi,

I noticed that when querying Marabou using MarabouNetwork.solve() with lower and upper bound properties (as set by MarabouNetwork.setLowerBound() and MarabouNetwork.setUpperBound()), MarabouNetwork.solve() does not terminate when the difference between the lower bound and upper bound is equal to DEFAULT_EPSILON_FOR_COMPARISON.

Is this expected behavior, or is it a bug? Moreover, why would this happen?

Thank you.

**Comment by SuryaB1** [comment]
I have spent some time investigating this issue and have found that this issue is a specific case of a more general issue that I have discussed more clearly in Issue #666.

**Comment by wu-haoze** [comment]
Closing as #666 is resolved.
