### ISSUE TITLE
Drastic runtime differences for MarabouNetwork.solve() with minor query changes

### ISSUE THREAD

**Issue by SuryaB1** [NeuralNetworkVerification/Marabou#666]
Hi,

The following code for querying bound-related properties of a network to Marabou results in drastically different runtimes among seemingly minor query changes. 

Specifically, the following bound-based query script as given results in a very long runtime (>3 hours)—the execution gets stuck at the `network.solve(...)` step. For context, the network that is read sets the first output variable to 0 if the input value is <= 0, or to 1 otherwise.

However, whenever the output variable's lower bound is greater than 0.000005 as indicated in the comments below, the script executes successfully within seconds and accurately indicates that there are no satisfying values.

These runtime differences seem strange and unexpected, especially since I also noticed that output variable lower bound values smaller than 0.000005 do not cause nonterminating runtimes when I set the upper bound of the input variable to be various values above 0 (in other words, no issues for the `SAT` case). Is there some sort of precision limit at 0.00005 for the `UNSAT` query case?

Or could this be a bug? Thank you for clarifying.

```python
from maraboupy import Marabou

TF_NN_FILENAME = "saved_models/sign_classif_nn_no-softmax" # Zipped folder is attached to this post

### Read network
network = Marabou.read_tf(filename = TF_NN_FILENAME, modelType="savedModel_v2")
inputVars = network.inputVars[0][0]
outputVars = network.outputVars[0].flatten()

### Set query's input variable bounds
network.setLowerBound(inputVars[0], -999.999995)
network.setUpperBound(inputVars[0], 0.0) # finds satisfying example when upper bound is above 0.0.

### Set query's output variable bounds
lowerBound = 0.000005 # works when greater than the current value, but runs for a long time when <= 0.000005
network.setLowerBound(outputVars[0], lowerBound)

### Query Marabou
options = Marabou.createOptions(snc=False)
exitCode, vals, stats = network.solve(verbose=False, options=options)
print("vals:", vals)
```

[sign_classif_nn_no-softmax.zip](https://github.com/NeuralNetworkVerification/Marabou/files/12403671/sign_classif_nn_no-softmax.zip)

**Comment by SuryaB1** [comment]
Here is another case that causes the query to not terminate in an expected time:

```python
from maraboupy import Marabou

TF_NN_FILENAME = "saved_models/sign_classif_nn_no-softmax" # Zipped folder is attached to this post

### Read network
network = Marabou.read_tf(filename = TF_NN_FILENAME, modelType="savedModel_v2")
inputVars = network.inputVars[0][0]
outputVars = network.outputVars[0].flatten()

### Set query's input variable bounds
network.setLowerBound(inputVars[0], 0.00001)
network.setUpperBound(inputVars[0], 1000.0)

### Set query's output variable bounds
upperBound = 0
network.setUpperBound(outputVars[0], upperBound)

### Query Marabou
options = Marabou.createOptions(snc=False)
exitCode, vals, stats = network.solve(verbose=False, options=options)
print("vals:", vals)
```

**Comment by SuryaB1** [comment]
I initially suspected the non-terminating issue had something to do with bounds being too precise, but the following additional successful and unsuccessful cases, respectively, show otherwise.

_Successful query accurately returning UNSAT:_
```python
from maraboupy import Marabou

TF_NN_FILENAME = "saved_models/sign_classif_nn_no-softmax"

### Read network
network = Marabou.read_tf(filename = TF_NN_FILENAME, modelType="savedModel_v2")
inputVars = network.inputVars[0][0]
outputVars = network.outputVars[0].flatten()

### Set query's input variable bounds
network.setLowerBound(inputVars[0], -999.99999)
network.setUpperBound(inputVars[0], -2.5247573739247027e-14)

### Set query's output variable bounds
lowerBound = 0.00001
network.setLowerBound(outputVars[0], lowerBound)

### Query Marabou
options = Marabou.createOptions(snc=False)
exitCode, vals, stats = network.solve(verbose=False, options=options)
print("vals:", vals)
```

_Unsuccessful (non-terminating) query that should return UNSAT:_
```python
from maraboupy import Marabou

TF_NN_FILENAME = "saved_models/sign_classif_nn_no-softmax"

### Read network
network = Marabou.read_tf(filename = TF_NN_FILENAME, modelType="savedModel_v2")
inputVars = network.inputVars[0][0]
outputVars = network.outputVars[0].flatten()

### Set query's input variable bounds
network.setLowerBound(inputVars[0], 9.999999974752427e-06)
network.setUpperBound(inputVars[0], 1000.0)

### Set query's output variable bounds
upperBound = 0
network.setUpperBound(outputVars[0], upperBound)

### Query Marabou
options = Marabou.createOptions(snc=False)
exitCode, vals, stats = network.solve(verbose=False, options=options)
print("vals:", vals)
```

**Comment by SuryaB1** [comment]
After some investigation, I found that I am only able to consistently avoid this non-terminating issue when using values strictly greater than 0.00001 (e.g. 0.000011, 0.00002, 0.3, 4, etc.) for query bounds. Additionally, using values less than `DEFAULT_EPSILON_FOR_COMPARISONS` for bounds presents a different issue: Marabou considers these values to be equivalent to 0, but I am guessing this is expected behavior given that there is such a variable assigned to it. However, it would be helpful to include relevant details regarding `DEFAULT_EPSILON_FOR_COMPARISONS` in an appropriate section of the documentation.

Why do any values less than or equal to 0.00001 and greater than or equal to `DEFAULT_EPSILON_FOR_COMPARISONS` for bounds cause this non-terminating issue during the UNSAT case? Is this a bug? Thank you for clarifying.

**Comment by wu-haoze** [comment]
Hi @SuryaB1 , thanks for discovering this issue. I took a look and discovered that this is indeed a "performance bug". The issue is that when the value is small, the preprocessor, which populate all bounds throughout the network until a fixpoint, does not terminate. I believe the preprocessor currently does not have termination guarantee, and therefore, I added a maximal number of iterations in the preprocessor to avoid the issue you see in this PR (#675 ).

**Comment by SuryaB1** [comment]
Hi @wu-haoze, thank you for fixing the issue!

After pulling and testing the merged changes, queries with bound values less than or equal to 0.00001 and greater than `DEFAULT_EPSILON_FOR_COMPARISONS` are no longer non-terminating, but, after some experimentation involving the same code given in my earlier comments of this Issue, it appears that these values are treated as equivalent to 0. Is this expected behavior?
