### ISSUE TITLE
Bug: Using minimal bound properties in query results in UNSAT for SAT query with Python API

### ISSUE THREAD

**Issue by SuryaB1** [NeuralNetworkVerification/Marabou#674]
Hi,

I am experiencing a similar issue to #669 where I have a query that is clearly SAT, but MarabouNetwork.solve() returns UNSAT. The only differences with this issue compared to #669 are that I am using bound properties in the query rather than equations and that I am using MarabouNetwork.solve().

This is the query:
```python3
from maraboupy import Marabou

# The following netowrk outputs 0 if the input is within the unit square 
#    bounded by (0,0), (0,1), (1,0), (1,1); otherwise outputs 1
TF_NN_FILENAME = "unit-sqr_classif_nn"

### Read network
network = Marabou.read_tf(filename = TF_NN_FILENAME, modelType="savedModel_v2")
inputVars = network.inputVars[0][0]
outputVars = network.outputVars[0].flatten()

### Set query's input variables' bounds
network.setLowerBound(inputVars[0], 0)
network.setUpperBound(inputVars[0], -0.0001)
network.setLowerBound(inputVars[1], -999.9999)
network.setUpperBound(inputVars[1], -0.0001)

### Output variable is unbounded

### Query Marabou
options = Marabou.createOptions(snc=False)
exitCode, vals, stats = network.solve(verbose=False, options=options)
```

The neural network file (zipped):
[unit-sqr_classif_nn.zip](https://github.com/NeuralNetworkVerification/Marabou/files/12550533/unit-sqr_classif_nn.zip)

**Comment by wu-haoze** [comment]
network.setLowerBound(inputVars[0], 0)
network.setUpperBound(inputVars[0], -0.0001)

It seems you set the upper bound to be lower than the lower bound, which is unsatisfiable.
