### ISSUE TITLE
Could you show me examples about reachability queries?

### ISSUE THREAD

**Issue by dongfeicui** [NeuralNetworkVerification/Marabou#678]
Maybe in the [example](https://github.com/NeuralNetworkVerification/Marabou/blob/master/maraboupy/examples/2_ONNXExample.py), the first example wants to show reachability queries but I am confuesd. Why the solver just print a single X value not a range?

![image](https://github.com/NeuralNetworkVerification/Marabou/assets/60336738/e85dc3f1-47f7-43b8-857a-1da99b7344dd)

**Comment by dongfeicui** [comment]
hello! could you solve this problem? please @guykatzz

**Comment by guykatzz** [comment]
Hello,
Marabou's output is either UNSAT, or SAT and a satisfying assignment,
depending on the query. It doesn't compute output ranges. If you wanted to,
you could repeatedly query Marabou and perform a binary search; e.g., if
y>3 is SAT and y>4 is UNSAT, you know that y's upper bound is somewhere
between 3 and 4, and you can narrow this range down using additional
queries.

Kind regards,
Guy
