### ISSUE TITLE
Error with MarabouCore.Equation

### ISSUE THREAD

**Issue by Peipi98** [NeuralNetworkVerification/Marabou#680]
Hello, I am using `MarabouCore.Equation(MarabouCore.Equation.GE)` to set constraints, but an error is occurring when I am launching the solver:
![tg_image_1731800680](https://github.com/NeuralNetworkVerification/Marabou/assets/39802340/76ab0eac-3f1e-406f-94c7-70cbb0c06115)

**Comment by idan0610** [comment]
Hello,

For now, you should not use the MarabouCore.Equation class for constraint coding, but the MarabouUtils.Equation class (both of which have the same interface). It is possible that in the future this will change, and the MarabouUtils.Equation class will be deprecated.

Could you try using MarabouUtils.Equation for now, and see if the problem still happens?

**Comment by SuryaB1** [comment]
I encountered this issue before and came to the conclusions found in Issue #652 . ```MarabouUtils.Equation(MarabouCore.Equation.GE)``` works.

The maraboupy examples have not yet been updated to reflect this.
