### ISSUE TITLE
Failed Queries when performing Property Inference

### ISSUE THREAD

**Issue by Peipi98** [NeuralNetworkVerification/Marabou#686]
Hello, I have this error when running a solver with constraints on hidden neurons:

```Number of variables: 1095
Number of lower bounds: 1095
Number of upper bounds: 1095
Number of equations: 211
Number of non-linear constraints: 100
Engine: Caught a MarabouError. Code: 3. Message:  !
Input query has been saved as failedMarabouQuery.ipq. Please attach the input query when you open the issue on GitHub.
```

System specs:
- MacBook Pro 2020
- MacOS Sonoma 14.0
- RAM: 8GB
- CPU: M1 8-core (arm64)

[utils_errors.zip](https://github.com/NeuralNetworkVerification/Marabou/files/12867170/utils_errors.zip)

You can find the mentioned file in the attachment.
The input query is simply composed by the output of the ReLUs, for each of them, and I invoke a decision proceduree (i.e. prove that P(F(X))=groundtruth holds by solving for P(F(X))≠groundtruth).

**Comment by idan0610** [comment]
It seems that this bug no longer exists in the latest version, so this issue is closed.
