### ISSUE TITLE
Questions about ACASXU ONNX and INPUT BATCH SIZE 

### ISSUE THREAD

**Issue by ZengyuLiu23** [NeuralNetworkVerification/Marabou#688]
Hello, thanks for providing such a verification tool for everyone to use. 

I want to call the tool while verifying on a given network (onnx format) that a given property is satisfied within a large number of different input interval ranges. I've successfully configured marabopy and tested it all according to the documentation. 

I have two questions that I would like to be answered and confirmed.

1. Is it not possible to directly support the ACASXU-related ONNX benchmark now, and do I need to extend the sub operation? If so, how do I change it? 
During the operation(I rewrote 2_ONNXExample.py):
...
filename = "../../resources/onnx/acasxu/ACASXU_experimental_v2a_2_7.onnx"
network = Marabou.read_onnx(filename)
...
I got this error message:
NotImplementedError: Operation Sub not implemented

2. I noticed that when setting the range of the input variables, the first dimension is reserved as batch_size. Does the current tool support the batch_size&gt;1 situation? That is, given a property and a network, can the current tool validate multiple different input spaces at the same time? If not, how can I modify it to support it?

Hope to be able to get your reply, your help is important to me. Good luck in your work.

**Comment by wu-haoze** [comment]
Hi @ZengyuLiu23 , I believe Sub is now implemented. We don't support support batch size > 1. You would need to invoke Marabou multiple times, at least for now
