### ISSUE TITLE
Marabou outputs error messages on `stdout` rather than `stderr`

### ISSUE THREAD

**Issue by MatthewDaggitt** [NeuralNetworkVerification/Marabou#714]
Currently when Marabou errors, it outputs the messages to the standard output stream instead of the standard error stream. This makes interacting it with external programs a little tricky.

I haven't yet investigated when and where it's doing this.

**Comment by wu-haoze** [comment]
Hi @MatthewDaggitt , I believe it's because of this:

https://github.com/NeuralNetworkVerification/Marabou/blob/282efe406e0b64fdb9c25a28437b93523e441224/src/engine/MarabouMain.cpp#L129-L136

I agree we should print this to stderr.  Please feel free to create a PR if you have time.
