### ISSUE TITLE
Test error and 'maraboupy.MarabouCore' error

### ISSUE THREAD

**Issue by jinqiang-yu** [NeuralNetworkVerification/Marabou#721]
There is an error shown as below: 

```
The following tests FAILED:
	 28 - Test_SumOfInfeasibilitiesManager (Failed)
Errors while running CTest
make[2]: *** [build-tests] Error 8
make[1]: *** [CMakeFiles/build-tests.dir/all] Error 2
make: *** [all] Error 2
```

when  I am on the last next shown below:
```
To build build both Marabou and Maraboupy using CMake, run:

cd path/to/marabou/repo/folder
mkdir build 
cd build
cmake .. -DBUILD_PYTHON=ON
cmake --build .
```

**Comment by wu-haoze** [comment]
Hi @jinqiang-yu , please ignore this error for now. It turns out that that particular test makes certain assumptions that do not hold across all platforms. I'll submit a fix to this issue.

**Comment by jinqiang-yu** [comment]
Thank you. When I tried `from maraboupy import Marabou` in Python, I got the following error: `aModuleNotFoundError: No module named 'maraboupy.MarabouCore'`

**Comment by wu-haoze** [comment]
Hi @jinqiang-yu  please add Marabou/ to the system path.

```
import sys
sys.append(“path/to/Marabou”)
from maraboupy import …
```

**Comment by jinqiang-yu** [comment]
> Hi @jinqiang-yu please add Marabou/ to the system path.
> 
> ```
> import sys
> sys.append(“path/to/Marabou”)
> from maraboupy import …
> ```

I try the below:
```
import sys
sys.path.append("path/to/Marabou")
import maraboupy
from maraboupy import Marabou
```

I still got the same error:
```
from maraboupy.MarabouCore import *
ModuleNotFoundError: No module named 'maraboupy.MarabouCore'
```

**Comment by jinqiang-yu** [comment]
I used a wrong version of Python. It works for me now when I use the correct version of Python.

**Comment by MatthewDaggitt** [comment]
It should work in versions 3.8-3.12. You will however need to use the same version of Python that you installed it with. Glad it's working for you now, so closing.
