### ISSUE TITLE
C++ ONNX parser crashes on a sigmoid network

### ISSUE THREAD

**Issue by wu-haoze** [NeuralNetworkVerification/Marabou#744]
The C++ ONNX parser is unable to handle the network attached below.

Here is the output running the command `./build/Marabou net.onnx prop.vnnlib`

> Network: net.onnx
> Floating point exception (core dumped)

[example.zip](https://github.com/NeuralNetworkVerification/Marabou/files/14275032/example.zip)

The Python ONNX parser is able to process this network and the property. On a separate note, it takes about 20 seconds before this error is thrown, but the python API can solve this in about 3.5 seconds. I'm wondering why this is the case. The network is not very large.

**Comment by MatthewDaggitt** [comment]
Slowness is due to `gemmEquations` and what I assume is a lot of `broadcastIndex` and `packIndices` calls...

**Comment by MatthewDaggitt** [comment]
The crash seems to be in the `Reshape` node.
