### ISSUE TITLE
Upgrade to using C++17

### ISSUE THREAD

**Issue by MatthewDaggitt** [NeuralNetworkVerification/Marabou#766]
In order to support Pytorch (see #754), we need to upgrade from C++11 to C++17. This issue is to discuss.

**Comment by MatthewDaggitt** [comment]
Heads up that the version seems to be hard-coded in:
- `download_boost.sh`

**Comment by wu-haoze** [comment]
Turns out the 11 in pybind11 is the lower limit. pybind11 works with versions after C11.

For boost, a flag needs to be set to not use deprecated operations.
