### ISSUE TITLE
 return all input-output pairs that satisfy the given range

### ISSUE THREAD

**Issue by chenyi10** [NeuralNetworkVerification/Marabou#793]
`filename` = "./data/models/model_epoch_999"

OPT = Marabou.createOptions(timeoutInSeconds=10,verbosity=0)

inputNames = ['Placeholder']
outputName = ['Identity']
network = Marabou.read_tf(filename=filename, modelType='savedModel_v2')

inputVars = network.inputVars[0][0]
outputVars = network.outputVars[0][0]

for i in range(8):
    for j in range(10):
        network.setLowerBound(inputVars[i][j],-100)
        network.setUpperBound(inputVars[i][j],100)

for k in range(8):
    network.setLowerBound(outputVars[k][0], -100)
    network.setUpperBound(outputVars[k][0], 100)

exitCode, vals, stats = network.solve(filename="",options=OPT)

How to make it return all input-output pairs that satisfy the given range?

**Comment by chenyi10** [comment]
Thanks!Is the one-dimensional convolutional network not supported for validation? @wu-haoze

**Comment by wu-haoze** [comment]
Yeah, we haven't supported it yet (https://github.com/NeuralNetworkVerification/Marabou/issues/723).

**Comment by chenyi10** [comment]
if i want to Verify the one-dimensional convolutional network，Do you hava some ideas @wu-haoze

**Comment by wu-haoze** [comment]
> if i want to Verify the one-dimensional convolutional network，Do you hava some ideas @wu-haoze

I think other than us actually implementing the parsing of 1-d convolution, there won't be an easy solution. I don't have a guaranteed timeline for this though. One possible route is to somehow convert the convolutional network to a fully connected one. This might be possible using the ONNX package. I'm not aware whether there is a tool that automatically does this.

**Comment by chenyi10** [comment]
i converted the convolutional network to a fully connected one,but i still cannot use marabou to verify it ,some operations ,such as "shape" have not been implemented.
Thanks for your help!  @wu-haoze

**Comment by chenyi10** [comment]
I converted the convolutional network to a fully connected one,but I couldnot use marabou to verify it ,some operations such as "shape gatherv2 Prod pack" havenot been implemented.
Thanks for your  help!@wu-haoze

**Comment by wu-haoze** [comment]
@chenyi10 is your network in the onnx format? If so, perhaps it’s worth trying onnxsim to get rid of some constant operators: https://github.com/daquexian/onnx-simplifier

If it didn’t work, feel free to share the network with me and I can try to add the missing operators post simplication.

**Comment by chenyi10** [comment]
sorry!bother you again,when i run cmake --build ./ Error comes,
[ 11%] Built target MarabouHelper
[ 21%] Built target MarabouHelperTest
[ 21%] Linking CXX executable Test_IncrementalLinearization
/usr/bin/ld: ../../libMarabouHelperTest.a(OptionParser.cpp.o): in function `OptionParser':
/home/gpu/chenyi/Marabou/src/configuration/OptionParser.cpp:31: undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
/usr/bin/ld: /home/gpu/chenyi/Marabou/src/configuration/OptionParser.cpp:32: undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
/usr/bin/ld: /home/gpu/chenyi/Marabou/src/configuration/OptionParser.cpp:33: undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
/usr/bin/ld: /home/gpu/chenyi/Marabou/src/configuration/OptionParser.cpp:34: undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
/usr/bin/ld: ../../libMarabouHelperTest.a(OptionParser.cpp.o): in function `basic_command_line_parser':
/home/gpu/chenyi/Marabou/tools/boost-1.84.0/installed/include/boost/program_options/detail/parsers.hpp:26: undefined reference to `boost::program_options::detail::cmdline::cmdline(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)'
/usr/bin/ld: ../../libMarabouHelperTest.a(OptionParser.cpp.o): in function `boost::program_options::variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const':
/home/gpu/chenyi/Marabou/tools/boost-1.84.0/installed/include/boost/program_options/variables_map.hpp:155: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/bin/ld: ../../libMarabouHelperTest.a(OptionParser.cpp.o): in function `boost::program_options::typed_value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>::name() const':
/home/gpu/chenyi/Marabou/tools/boost-1.84.0/installed/include/boost/program_options/detail/value_semantic.hpp:22: undefined reference to `boost::program_options::arg[abi:cxx11]'
/usr/bin/ld: ../../libMarabouHelperTest.a(OptionParser.cpp.o): in function `boost::program_options::typed_value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>::xparse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const':
/home/gpu/chenyi/Marabou/tools/boost-1.84.0/installed/include/boost/program_options/detail/value_semantic.hpp:184: undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)'
/usr/bin/ld: ../../libMarabouHelperTest.a(OptionParser.cpp.o): in function `boost::program_options::typed_value<int, char>::name[abi:cxx11]() const':
/home/gpu/chenyi/Marabou/tools/boost-1.84.0/installed/include/boost/program_options/detail/value_semantic.hpp:22: undefined reference to `boost::program_options::arg[abi:cxx11]'
/usr/bin/ld: ../../libMarabouHelperTest.a(OptionParser.cpp.o): in function `void boost::program_options::validate<int, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, int*, long)':
/home/gpu/chenyi/Marabou/tools/boost-1.84.0/installed/include/boost/program_options/detail/value_semantic.hpp:95: undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: ../../libMarabouHelperTest.a(OptionParser.cpp.o): in function `validation_error':
/home/gpu/chenyi/Marabou/tools/boost-1.84.0/installed/include/boost/program_options/errors.hpp:378: undefined reference to `boost::program_options::validation_error::get_template[abi:cxx11](boost::program_options::validation_error::kind_t)'
/usr/bin/ld: /home/gpu/chenyi/Marabou/tools/boost-1.84.0/installed/include/boost/program_options/errors.hpp:378: undefined reference to `boost::program_options::error_with_option_name::error_with_option_name(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
/usr/bin/ld: ../../libMarabouHelperTest.a(OptionParser.cpp.o): in function `boost::program_options::typed_value<float, char>::name[abi:cxx11]() const':
/home/gpu/chenyi/Marabou/tools/boost-1.84.0/installed/include/boost/program_options/detail/value_semantic.hpp:22: undefined reference to `boost::program_options::arg[abi:cxx11]'
/usr/bin/ld: ../../libMarabouHelperTest.a(OptionParser.cpp.o): in function `void boost::program_options::validate<float, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, float*, long)':
/home/gpu/chenyi/Marabou/tools/boost-1.84.0/installed/include/boost/program_options/detail/value_semantic.hpp:95: undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: ../../libMarabouHelperTest.a(OptionParser.cpp.o): in function `std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > boost::program_options::to_internal<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)':
/home/gpu/chenyi/Marabou/tools/boost-1.84.0/installed/include/boost/program_options/detail/convert.hpp:79: undefined reference to `boost::program_options::to_internal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: ../../libMarabouHelperTest.a(OptionParser.cpp.o):(.rodata._ZTVN5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcEE[_ZTVN5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcEE]+0x38): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
/usr/bin/ld: ../../libMarabouHelperTest.a(OptionParser.cpp.o):(.rodata._ZTVN5boost15program_options11typed_valueIicEE[_ZTVN5boost15program_options11typed_valueIicEE]+0x38): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
/usr/bin/ld: ../../libMarabouHelperTest.a(OptionParser.cpp.o):(.rodata._ZTVN5boost10wrapexceptINS_15program_options16validation_errorEEE[_ZTVN5boost10wrapexceptINS_15program_options16validation_errorEEE]+0x60): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/bin/ld: ../../libMarabouHelperTest.a(OptionParser.cpp.o):(.rodata._ZTVN5boost15program_options16validation_errorE[_ZTVN5boost15program_options16validation_errorE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/bin/ld: ../../libMarabouHelperTest.a(OptionParser.cpp.o):(.rodata._ZTVN5boost10wrapexceptINS_15program_options20invalid_option_valueEEE[_ZTVN5boost10wrapexceptINS_15program_options20invalid_option_valueEEE]+0x60): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/bin/ld: ../../libMarabouHelperTest.a(OptionParser.cpp.o):(.rodata._ZTVN5boost15program_options20invalid_option_valueE[_ZTVN5boost15program_options20invalid_option_valueE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/bin/ld: ../../libMarabouHelperTest.a(OptionParser.cpp.o):(.rodata._ZTVN5boost15program_options11typed_valueIfcEE[_ZTVN5boost15program_options11typed_valueIfcEE]+0x38): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/cegar/CMakeFiles/Test_IncrementalLinearization.dir/build.make:216：src/cegar/Test_IncrementalLinearization] 错误 1
make[1]: *** [CMakeFiles/Makefile2:3446：src/cegar/CMakeFiles/Test_IncrementalLinearization.dir/all] 错误 2
make: *** [Makefile:95：all] 错误 2
