### ISSUE TITLE
Failing 5 tests when building with Gurobi optimizer

### ISSUE THREAD

**Issue by ggustavs** [NeuralNetworkVerification/Marabou#803]
Following the install steps listed [here](https://github.com/NeuralNetworkVerification/Marabou/blob/master/README.md) I ran this command:

`cmake --build ./`

During the build process, I got this output:

93% tests passed, 5 tests failed out of 76

Label Time Summary:
basis_factorization unit       =   0.98 sec*proc (14 tests)
cegar unit                     =   0.26 sec*proc (1 test)
common unit                    =   0.91 sec*proc (19 tests)
engine unit                    =   6.93 sec*proc (30 tests)
network_level_reasoner unit    =   1.18 sec*proc (4 tests)
parser unit                    =   3.33 sec*proc (2 tests)
proofs unit                    =   0.73 sec*proc (5 tests)
query_loader unit              =   0.26 sec*proc (1 test)

Total Test time (real) =   3.26 sec

The following tests FAILED:
         17 - Test_MILPEncoder (Failed)
         49 - Test_GurobiWrapper (Failed)
         73 - Test_OnnxParser (Failed)
         74 - Test_VnnLibParser (Failed)
         79 - Test_ParallelSolver (Failed)
         
After inspecting the full output, I saw that the tests kept failing with this error message:
"Set parameter Username"

I am trying to build Marabou on Ubuntu 22.04.4 LTS running inside of a docker container.
The installed Gurobi version is 9.5.1
The cmake verison is 3.20.0

Please ask if you need any more information.
I can also provide the image if that would help.

**Comment by wu-haoze** [comment]
Hi @ggustavs , this usually happens when the Gurobi license is not found. Once you have a working license. Before building, invoke 

export GRB_LICENSE_FILE=path/to/license/file

**Comment by wu-haoze** [comment]
The fact you’re using in a docker could also be the problem. I’m not sure the license might be specific to a particular MAC address (I’m not sure whether docker image has its own virtual MAC address).
